---
title: "Kew monograph 02: More Kew specimens from Nina's product pages"
author:
  name: Lemuria
  affiliation:
    - name: Independent researcher; Manila, Philippines
  email: lemuria@lemuria.ph
license: CC BY-SA
journal:
  title: "Lemuria's (Informal) Journal of Clothing Taxonomy"
date: 2026-04-11
lang: en
execute: 
  freeze: true
publisher-id: lict2026.0008
abstract: |
  We build on the monograph of the Kew dresses with additional descriptions for the Kew dress specimens on Nina Lee's product pages; including the first skirt species description in the entire taxonomy, *Kewisicasa laria*. In total, we describe 21 new species and six new subgenera; and populate the genus *Kewisicasa* with new specimens.
bibliography: ninas_kews.bib
number-sections: true
doi: 10.5281/zenodo.19466565
citation:
  author: Lemuria
  title: "Kew monograph 02: More Kew specimens from Nina's product pages"
  original-date: 2026-04-11
  publisher: Lemuria
  article-id: lict2026.0008
  publisher-place: Philippines
  doi: 10.5281/zenodo.19466565
format:
  html:
    format-links: false
    other-links:
      - text: PDF
        href: https://static.lemuria.ph/lct01/pdf/2026/2026.0008_ninas_kews.pdf
        icon: file-pdf
  aft-pdf:
    toc: true
    toc-depth: 3
    include-in-header:
      text: |
        \usepackage{forest}
keywords: kew dress, kewoidea, kewthidae, helikewidae, nina lee, clothing taxonomy, home sewing, sewing pattern
---

```{=latex}
\begin{multicols}{2}
```

## Background
<!-- FINALIZED 2026-04-11 -->
The Kew dress is now perhaps the most extensively-studied sewing pattern in the LCT-01. Earlier in March 2026, we published a 52-page monograph on the Kew dresses, which laid out the structure of Kew dress taxonomy and described over 47 species [@lemuria_taxonomy_2026].

The total count of Kew dress taxa now stands at
1 superfamily (Kewoidea);
5 families (Kewidae, Plesikewidae, Helikewidae, Kewthidae, and Kewcasaceae);
6 subfamilies (Kewbellinae, Kewthinae, Trunkewinae, Helikewinae, Plesikewinae, and Kewasalinae);
2 tribes (Helikewini, Helikewbellini, Kewthini);
19 genera (*Kewplicasa*, *Kewparacasa*, *Kewisicasa*, *Kewbellothea*, *Kewpepla*, *Kewthea*, *Kewthicata*, *Trunkewia*, *Helikewbellia*, *Helikewparabola*, *Helikewplicata*, *Helikewabotonia*, *Helikewisia*, *Kewasalia*, *Florankewia*, *Kewabotonia*, *Kewplicata*, *Kewparabola*, *Kewisia*);
8 subgenera; and 67 species.

Size is typically not considered a relevant morphological character for taxa due to its continuous, non-discrete nature. However, the sale of size ranges of sewing patterns as separate products constitutes discrete phylogenetic information, which is best suited for defining infrageneric taxa. The usage of infrageneric ranks originated in *Heleonora* Lemuria, 2026 (unpublished so far), encompassing the sleeveless variant of the Eleonora by Silversaga Patterns.

### Taxonomic history
<!-- FINALIZED 2026-04-11 -->
The large amount of Kew dresses on the Internet threatened to inflate the scope of @lemuria_taxonomy_2026 excessively; as such, we enacted a "species freeze" where new Kew specimens would be reserved for subsequent papers. We continue our research into the Kew dress as part of this paper, describing 21 new species, six new subgenera, and one new genus, *Kewisicasa*.

When authoring the Kew monograph, we focused primarily on makes of the pattern in the wild as opposed to official product photos, for a variety of reasons, such as not wanting to have the appearance of a reseller catalog^[This concern is a holdover from our internal MediaWiki site, where we embed images more freely than in the *Journal*. The academic paper format of the *Journal* extensively distinguishes it from a reseller listing or catalog.], and the anecdotal observation that third parties produce richer documentation than official product pages.

Originally, we were unable to identify the wearers of each holotype specimen beyond their first name. However, on April 3, our lead author decided to include a history of how Chang-Smith developed the expanded size ranges, and in the process, decided also to cite posts by Chang-Smith featuring many of the holotypes on Instagram that included information on the persons featured. Though not every single person was identifiable due to broken Instagram links or Imginn not having the requested profile, we were able to further confirm some identities by correlating them with filenames from the Nina Lee website.

Timestamps were also updated based on these posts; we inferred the old timestamps from the `v` variable on Shopify CDN images, which likely do not reflect the image's actual creation date.

### Terminology
<!-- FINALIZED 2026-04-11 -->
The term "expansion" is rather ambiguous in this context, as it can either refer to the Kew dress expansion pack, which adds two skirt options, or to the expanded size range.

Thus, we use four standardized terms for the four Kew patterns.


<!-- TODO: Verify that these terms are being used consistently. Tag with "checked for Concern 1" -->
<!-- CONCERN 1 passed everywhere; turns out the Expansa subgenera just say "size 21 and above" -->
* Kew 6-20 refers to the "base" Kew pattern, from UK sizes 6 to 20.
* Kew 16-28 refers to the "base" Kew pattern, from UK sizes 16 to 28.
* Kew expansion 6-20 refers to the expansion pack, from UK sizes 6 to 20.
* Kew expansion 16-28 refers to the expansion pack, from UK sizes 16 to 28.

<!-- | - | 6-20 | 16-28
|---|---|---|
| Base | Kew 6-20
| Expansion | Kew 6-20 expanded
 -->

### History of the expansion
The Kew dress's history is extensively discussed in @lemuria_taxonomy_2026. Here, we focus on Nina Chang-Smith's expansion of her size range to UK size 28.

The first public evidence that Chang-Smith was working on the expansion came in October 2019, when she posted an advertisement looking for a UK size 20 fit model to review her adjusted base size with, before grading. In the advertisement, Chang-Smith specified a model with a bust of ~116 cm (46 in), waist of ~98 cm (39 in), and hip of ~124 cm (49 in)^[Exact measurement methodology unknown. We assume that the waist and hip measurements are that of the body's circumference. Our lead author is male and does not trust himself to make assumptions regarding bust size measurements.] [@changsmith2019].

Chang-Smith worked on her expanded ranges in reverse-chronological pattern release order; recruiting testers for the Southbank, Carnaby, and Mayfair in January 2020 [@nlpt_scm]; and later in September, the Kew [@nlpt_kew]. On February 19, 2021, the Kew 16-28 pattern was released. <!-- FIXME: When was Kew 16-28 released, when was Kew expansion 16-28 released? -->

## Methods
<!-- FINALIZED 2026-04-11 -->
<!-- Checked for Concern 1, 2026-04-11; PASS -->
The lead author conducted his research on a computer running Ubuntu 24.04, with the XFCE desktop environment. He used the SHA2-256 algorithms to compute the cryptographic hashes of the photographic specimens he examined for species descriptions. He used Firefox 139.0.4. His monitor is a 55.8 cm (22 in) wide, 30.48 cm (12 in) tall, 63.5 cm (25 in) diagonal monitor, the NVISION S2515-B 25" IPS with a 100Hz refresh rate. He is not colorblind. He is near sighted and wears glasses.

As our lead author had no Instagram account, he used Imginn, an online service that allows Instagram to be viewed without an account.

Specimens were collected from Nina Lee's product pages on <https://ninalee.co.uk>. All images were in JPG format. The website uses Shopify as its underlying platform and image storage; EXIF metadata is scarce, and this removal is likely consistent with internal Shopify server-side upload processing code. EXIF metadata was checke d using ExifTool version 12.76.

### `lct01-notes`
<!-- FINALIZED 2026-04-11 -->
<!-- Checked for Concern 1, 2026-04-11; PASS -->
During work on this paper, the author created a new tool that automatically generates Quarto template text from structured YAML data. This allows the data to exist in a structured format for future processing with other systems, and further improves standardization. Descriptions and remarks remain human-written; with less administrative and menial work comes the opportunity for more creative work.

A paper dedicated solely to this software has not been started, but may be authored someday. The tool was developed during the creation of this paper; as such, not all entries were automatically templated. YAML files used to generate some of the template texts are provided with the paper.

### Checksums
<!-- FINALIZED 2026-04-11 -->
<!-- Checked for Concern 1, 2026-04-11; PASS -->
The versions of the `sha256sum` and `openssl` utilities on his system at the time of the paper are given in the below terminal output:

```{=latex}
\end{multicols}
```

::: {#fig-sha256sum}
```
$ sha256sum --version
sha256sum (GNU coreutils) 9.4
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Ulrich Drepper, Scott Miller, and David Madore.
$ openssl --version
OpenSSL 3.5.0 8 Apr 2025 (Library: OpenSSL 3.5.0 8 Apr 2025)
$ sha256sum /usr/bin/sha256sum /usr/bin/openssl
f293048f656688883ee919eb3f4b12926aaa13362de0eb6e3b5716b915b18b35  /usr/bin/sha256sum
724acbe911513d13f52bae0b8969b20336cd8618fc67898a6bf7847bf1a270ad  /usr/bin/openssl
```

A hash of the sha256sum and openssl utilities on the lead author's computer.
:::

## Trees
<!-- FINALIZED 2026-04-11 -->
<!-- Checked for Concern 1, 2026-04-11; PASS -->
As previously stated in @lemuria_taxonomy_2026, the hybrid phenetic&ndash;phylogenetic structure of the LCT-01 causes the Kew dresses to scatter polyphyletically across the tree. The updated Kew trees are presented below.

```{r}
#| results: asis
#| fig-show: asis
#| message: false

library(treeio)
library(ggtree)
library(ggplot2)
library(ggtreeExtra)
library(dplyr)
library(ggtext)
library(knitr)

text <- "((((((((Kewplicasa,Kewparacasa,(Kewisicasa_laria,(Kewisicasa_jessae,Kewisicasa_mandia)Kewisicasa_subg._Expansa)Kewisicasa[&&NHX:rank=genus])Kewcasaceae[&&NHX:subtree_root=yes])Ventracasales)Ventracasidna)Botonicasida)Castula)Suprapatella)Subpelvia,((((((((Kewbellothea_mottramia,Kewbellothea_lavendula,Kewbellothea_rubera)Kewbellothea_subg._Expansa,(Kewbellothea_aquacolor,Kewbellothea_autumna)Kewbellothea_subg._Ninae)Kewbellothea[&&NHX:rank=genus])Kewbellinae,((Kewpepla_lornae,Kewpepla_lornaebis,Kewpepla_mariae)Kewpepla[&&NHX:rank=genus],((Kewthicata_juliae)Kewthicata[&&NHX:rank=genus],(Kewthea_chantellae,Kewthea_evae,Kewthea_lornae,Kewthea_lornoblae,Kewthea_luscinia,Kewthea_modistaflora,(Kewthea_ruberabotonia,Kewthea_venetaflora)Kewthea_subg._Ninae,(Kewthea_hawkinsia,Kewthea_caledonia,Kewthea_eleanorae,Kewthea_lauraflora)Kewthea_subg._Expansa)Kewthea[&&NHX:rank=genus])Kewthini)Kewthinae)Kewthidae[&&NHX:subtree_root=yes])Vecobotonia)Vecostola)Manubristenta,(((((((Trunkewia_ninae,(Trunkewia_rosacrania,Trunkewia_rubera,Trunkewia_viridis)Trunkewia_subg._Illecebrosus)Trunkewia[&&NHX:rank=genus])Trunkewinae,((((Helikewbellia_melalourida,Helikewbellia_flutteria)Helikewbellia_subg._Ninae)Helikewbellia[&&NHX:rank=genus])Helikewbellini,(Helikewparabola,(Helikewplicata_ninae)Helikewplicata[&&NHX:rank=genus],(Helikewabotonia_lanata,Helikewabotonia_stadile)Helikewabotonia,(Helikewisia_aemilia,Helikewisia_ceciliae,Helikewisia_erinae,Helikewisia_irvinae,Helikewisia_kristinae,Helikewisia_mariae,Helikewisia_sarae,Helikewisia_roseatulipa,Helikewisia_amyboria,(Helikewisia_arbor,Helikewisia_quagga)Helikewisia_subg._Emmae)Helikewisia[&&NHX:rank=genus])Helikewini)Helikewinae)Helikewidae[&&NHX:subtree_root=yes])Helinina)Helistola)Scapamanica,((((((((Kewasalia_pimsia)Kewasalia[&&NHX:rank=genus])Kewasalinae,((Florankewia_libera,Florankewia_valentina)Florankewia[&&NHX:rank=genus],(Kewabotonia_eleanorae,Kewabotonia_elsae,Kewabotonia_nuptirachaelae,Kewabotonia_sarae,Kewabotonia_zingibera)Kewabotonia[&&NHX:rank=genus])Plesikewinae)Plesikewidae,(Kewplicata[&&NHX:rank=genus],Kewparabola[&&NHX:rank=genus],(Kewisia_bernicae,Kewisia_evae,Kewisia_fionae,Kewisia_genyae,Kewisia_kristinae,Kewisia_latae,Kewisia_lizae,Kewisia_mariae,Kewisia_modistaflora,Kewisia_modistarubera,Kewisia_rachaelae,Kewisia_reginarunae,Kewisia_sarae,(Kewisia_tropiki,Kewisia_roseafolia)Kewisia_subg._Ninae)Kewisia[&&NHX:rank=genus])Kewidae)Kewoidea[&&NHX:subtree_root=yes])Biligabotonia)Biligamentum)Bilourida)Umerostentida)Scapunatoria)Abtruncusa)Vestimentia;"

tree <- read.nhx(textConnection(text))

subtree_nodes <- tree@data %>%
  filter(subtree_root == "yes") %>%
  pull(node)

p <- ggtree(tree)

for (n in subtree_nodes) p <- collapse(p, n) + geom_point2(aes(subset=(node==!!n)), shape = 23, size=5, fill='red')

rootTree <- p + geom_tiplab(size = 3) +
  geom_richtext(
    aes(label = label),
    data = td_filter(!isTip),
    size = 2, na.rm = TRUE,
    fill = 'lightblue', label.color = 'white'
  ) + vexpand(1)

fig_height <- function(tr) max(3, min(length(tr@phylo$tip.label) * 0.25, 12))

plots <- list(
  list(p = rootTree, w = 12, h = 4, label = "Overview")
)

format_node_label <- function(label, rank) {
  if (!is.na(rank) && rank == "genus") {
    return(paste0("<i>", gsub("_", " ", label), "</i>"))
  }
  components <- unlist(strsplit(label, "_"))
  if (grepl("subg\\.", label)) {
    new_label <- paste0("<i>",components[1],"</i> subg. <i>",components[3],"</i>")
    return(new_label)
  }
  paste0(gsub("_", " ", label))
}

format_species <- function(label) {
  paste0(gsub("_", " ", label))
}

for (n in subtree_nodes) {
  subtree <- tidytree::tree_subset(tree, n, levels_back = 0)
  if (length(subtree@phylo$tip.label) < 2) next 
  
  root_taxon_node <- as_tibble(tree) |> filter(node == n)
  root_taxon <- root_taxon_node |> pull(label)
  p_sub <- ggtree(subtree) +
    geom_tiplab(size = 3, aes(label = mapply(format_species, label)), fontface = "italic") +
    geom_richtext(
      data = td_filter(!isTip),
      aes(label = mapply(format_node_label, label, rank)),
      size = 2, na.rm = TRUE,
      fill = 'lightblue', label.color = NA
    ) +
    hexpand(0.3) + vexpand(0.5)
  plots[[length(plots) + 1]] <- list(p = p_sub, w = 12, h = fig_height(subtree), label = root_taxon)
}

for (i in seq_along(plots)) {
  p <- plots[[i]]
  chunk <- knitr::knit_expand(
    text = c(
      "```{r fig-{{label}}, fig.height={{h}}, fig.width=8, fig.cap='{{label}}', echo=FALSE}",
      "plots[[{{i}}]]$p",
      "```"
    ),
    i = i,
    h = plots[[i]]$h,
    label = plots[[i]]$label
  )
  cat(knitr::knit(text = chunk, quiet = TRUE))
  cat("\n\n")
}
```

```{=latex}
\newpage
```

## Descriptions
<!-- Checked for Concern 1, 2026-04-11; PASS - IRRELEVANT: Helikewbellia is not from the Kew pattern, Kewbello is separate. -->
### Genus *Helikewbellia* {#sec-helikewbellia}
<!-- FINALIZED 2026-04-11 -->
***Helikewbellia*** Lemuria, 2026; first public desc.

**Diagnosis**: Phylogenetically, *Helikewbellia* is characterized by origin from the sleeveless variant of the Kewbello pattern; phenetically, the combination of the Kew sleeveless strappy bodice and Portobello trousers; and the presence of a dorsal medial zipper on the bodice. Bilateral ventral darts present from the third button to the bodice&ndash;skirt seam; bilateral sets of three seams at outward flare angle; bilateral pockets.

**Remarks**: There exist two phylogenetic pathways through which a sleeveless Kewbello may arise; from the Kewbello pattern itself (pathway 1), or an independent recombination of the Kew sleeveless dress bodice and the Portobello trousers, done without referencing the pattern (pathway 2). Pathway 2 remains unattested.

**Type species**: *Helikewbellia flutteria* (see @sec-helikewbellia-flutteria)

<!-- Template generated with lct01tools and manually filled in by humans! -->
### *Helikewbellia* subg. *Ninae* {#sec-helikewbellia-subg-ninae}
<!-- FINALIZED 2026-04-11 -->
***Helikewbellia* subgenus *Ninae*** Lemuria, 2026

**Diagnosis**: Phylogenetically, *Helikewbellia* subg. *Ninae* is defined by having been created by Nina Chang-Smith.

**Etymology**: *Nina* + *-ae*.

<!-- replace taxon with the name of the rank! -->
**Type species**: *Helikewbellia flutteria* (see @sec-helikewbellia-flutteria)

<!-- Template generated with lct01tools and manually filled in by humans! -->
#### *Helikewbellia melalourida* {#sec-helikewbellia-melalourida}
<!-- FINALIZED 2026-04-11 -->
***Helikewbellia melalourida*** Lemuria, 2026

**Holotype**: ***Nina 90381.248*** &mdash; Photograph.
EXIF metadata stripped.
*Helikewbellia melalourida* wb. Nina, unknown.
Angled ventral view. Subject's arms fully adducted, in pockets; ventral medial button row blends into fabric, visibility impeded.
&copy; Nina Chang-Smith or unknown photographer, all rights reserved.

* **Page**: @kewbello620
* **SHA2-256**: `00d5f66d76582d50e753f55b5b7d5c4f197703d159a0777293de27349064418c`
* **Raw image URLs**
  * **Original**: <https://www.ninalee.co.uk/cdn/shop/files/Nina_Lee_Kewbello_black_straps_side_view_pink_background.jpg?v=1722462174>
  * **IA**: <https://web.archive.org/web/20260405171750/https://www.ninalee.co.uk/cdn/shop/files/Nina_Lee_Kewbello_black_straps_side_view_pink_background.jpg?v=1722462174>

**Diagnosis**: *Helikewbellia melalourida* is characterized by a fabric with a black background, with white line drawings of houses and palm trees, consistent with upper-class coastal California communities.

**Remarks**: The description of the fabric as being similar to upper-class coastal California communities may be influenced by the lead author's knowledge that as of 2026, Nina Chang-Smith has lived in California since 2022.

**Etymology**: From Latin *melas* ("black") + Greek  λουρίδα (*lourída*, "strap"), referring to the black color of the straps.

**Specimens examined**:

* Holotype.
* *Nina 90381.276* &mdash; Photograph.
EXIF metadata stripped.
Dorsal view. Hair positioned ventrally.
*Helikewbellia melalourida* wb. Nina, unknown.
&copy; Nina Chang-Smith or unknown photographer, all rights reserved.
  * **Page**: @kewbello620
  * **SHA2-256**: `22c2db3b17bd839650280e8f4e51a98d75da5021d20c9c5358adc37894a36fa5`
  * **Raw image URLs**
    * **Original**: <https://www.ninalee.co.uk/cdn/shop/files/Nina_Lee_Kewbello_black_straps_back_view_pink_background.jpg?v=1722462174>
    * **IA**: <https://web.archive.org/web/20260405171750/https://www.ninalee.co.uk/cdn/shop/files/Nina_Lee_Kewbello_black_straps_back_view_pink_background.jpg?v=1722462174>

<!-- Template generated with lct01tools and manually filled in by humans! -->
#### *Helikewbellia flutteria* {#sec-helikewbellia-flutteria}
<!-- FINALIZED 2026-04-11 -->
***Helikewbellia flutteria*** Lemuria, 2026

**Holotype**: ***Nina 90387.475*** &mdash; Photograph.
EXIF metadata stripped.
*Helikewbellia flutteria* wb. Nina, unknown.
&copy; Nina Chang-Smith or unknown photographer, all rights reserved.

* **Page**: @kewbello620
* **SHA2-256**: `c9483d4b827b26e3f9cd41c381380dbe04ca28b2e8ba2ef41ea097d768242c2e`
* **Raw image URLs**
  * **Original**: <https://www.ninalee.co.uk/cdn/shop/files/Nina_Lee_Kewbello_yellow_straps_blue_background.jpg?v=1722462244>
  * **IA**: <https://web.archive.org/web/20260405171750/https://www.ninalee.co.uk/cdn/shop/files/Nina_Lee_Kewbello_yellow_straps_blue_background.jpg?v=1722462244>

**Diagnosis**: *Helikewbellia flutteria* is characterized by a flutter sleeve, with fabric attached to the lateral sides of the straps; and a fabric with a vague watercolor floral pattern, with a yellow background, with smaller amounts of pale orange and olive green color; and a ventral medial button row of five circular buttons with an interior curved square and four thread holes; and yellow thread.

**Remarks**: The classification of *Helikewbellia flutteria* may be a useful example in the eventual classification of Lauren Johnson's flutter Kew dress. 

**Etymology**: From English *flutter*, a word of Germanic origin + *-ia*, for a Latin feel.

**Specimens examined**:

* Holotype.
* *Nina 90387.478* &mdash; Photograph.
EXIF metadata stripped.
*Helikewbellia flutteria* wb. Nina, unknown.
&copy; Nina Chang-Smith or unknown photographer, all rights reserved.
  * **Page**: 
  * **SHA2-256**: `87425f5d907e3c01382b563e6e276bd506e838159014d2973a6b9d8fb3e79391`
  * **Raw image URLs**
    * **Original**: <https://www.ninalee.co.uk/cdn/shop/files/Nina_Lee_Kewbello_yellow_straps_blue_background_v2.jpg?v=1722462174>
    * **IA**: <https://web.archive.org/web/20260405171750/https://www.ninalee.co.uk/cdn/shop/files/Nina_Lee_Kewbello_yellow_straps_blue_background_v2.jpg?v=1722462174>

### Genus *Helikewisia*
<!-- FINALIZED 2026-04-11 -->
***Helikewisia*** Lemuria, 2026

See @lemuria_taxonomy_2026.

#### *Helikewisia roseatulipa*
<!-- FINALIZED 2026-04-11 -->
***Helikewisia roseatulipa*** Lemuria, 2026; sp. nov.

**Holotype**: *Kew 74024.100HR* &mdash; Photograph.
2067&times;2835.
EXIF metadata stripped.
Ventral view. Hair positioned dorsally.
*Helikewisia roseatulipa* wb. Amy.C., 2017.
&copy; Nina Chang-Smith or unknown photographer, 2017, all rights reserved.

* **Page**: See @kew6_20
* **SHA2-256**: `b27c74a092a9222518bb154f79468dd3caa0dd7f894dcdfd3730113885008202`
* **Raw image URLs**:
  * **Original**: <https://www.ninalee.co.uk/cdn/shop/products/Kew-Dress-V2-1.jpg?v=1680151814>
  * **IA**: <https://web.archive.org/web/20260326181302/https://www.ninalee.co.uk/cdn/shop/products/Kew-Dress-V2-1.jpg?v=1680151814>

**Diagnosis**: *Helikewisia roseatulipa* is characterized by its fabric pattern of pink tulips and green leaves against a white background and its ventral medial row of 15 shank button with no thread holes, with a wood-like surface.

**Etymology**: Portmanteau of Latin *rosea*, feminine form of *roseus* ("pink") + *Tulipa* L.

**Specimens examined**: See holotype information.

#### *Helikewisia amyboria*
<!-- FINALIZED 2026-04-11 -->
***Helikewisia amyboria*** Lemuria, 2026; sp. nov.

**Holotype**: *Kew 9018.1728*, person on left. See @sec-image-specimens.

**Diagnosis**: *Helikewisia amyboria* is characterized by its fabric pattern of trees with pink trunks and slight potato/brown/golden-colored leaves, and clouds and a ventral medial row of 15 circular buttons with four thread holes.

**Etymology**: Blend of *Amy* + Latin *arbor* ("tree"), as *Helikewisia arbor* is already used.

**Specimens examined**: See holotype information.

### Genus *Kewbellothea* {#sec-kewbellothea}
<!-- FINALIZED 2026-04-11 -->
***Kewbellothea*** Lemuria, 2026; first public desc.

**Diagnosis**: Phylogenetically, *Kewbellothea* is characterized by origin from the sleeved variant of the Kewbello pattern; phenetically, the combination of the Kew tea dress bodice and Portobello trousers; and the presence of a dorsal medial zipper on the bodice. Bilateral ventral darts present from the third button to the bodice&ndash;skirt seam; bilateral sets of three seams at outward flare angle; bilateral pockets.

**Remarks**: There exist two phylogenetic pathways through which a tea dress Kewbello may arise; from the Kewbello pattern itself (pathway 1), or an independent recombination of the Kew tea dress bodice and the Portobello trousers, done without referencing the pattern (pathway 2). Pathway 2 remains unattested.

**Type species**: *Kewbellothea aquacolor* (see @sec-kewbellothea-aquacolor)

### *Kewbellothea* subg. *Expansa* {#sec-kewbellothea-subg-expansa}
<!-- Checked for Concern 1, 2026-04-11; PASS -->
<!-- FINALIZED 2026-04-11 -->
***Kewbellothea* subgenus *Expansa*** Lemuria, 2026; subgen. nov.

**Diagnosis**: Phylogenetically, *Kewbellothea* subg. *Expansa* is defined by origin from size 21 and above of the Kewbello pattern. See @kewbello1628.

**Etymology**: From Latin *expansa*, feminine form of *expansus* ("expanded"), referring to the pattern's expanded size range..

<!-- replace taxon with the name of the rank! -->
**Type species**: *Kewbellothea mottramia* (see @sec-kewbellothea-mottramia)

<!-- Template generated with lct01tools and manually filled in by humans! -->
#### *Kewbellothea mottramia* {#sec-kewbellothea-mottramia}
<!-- FINALIZED 2026-04-11 -->
***Kewbellothea mottramia*** Lemuria, 2026; sp. nov.

**Holotype**: *Mottram 4958.194* &mdash;
Photograph. 1200&times;1646.
Ventral view. Subject's arms fully adducted. Hair positioned dorsally, dress unobscured. Outdoor lighting conditions, daytime; wooden building in background; dog in bottom right of image.
*Kewbellothea mottramia* wb. Eleanor.M., unknown.
&copy; Eleanor Mottram or unknown photographer, all rights reserved.

* **Page**: @kewbello1628
* **SHA2-256**: `3087d2aeeacba1075e2653eaf93d5f5b09f7bc6467a1d696ddb792696f012433`
* **Raw image URLs**
  * **Original**: <https://www.ninalee.co.uk/cdn/shop/files/NinaLeeKewbelloJumpsuitEleanorMottram.jpg?v=1696062971>
  * **IA**: <https://web.archive.org/web/20260405171751/https://www.ninalee.co.uk/cdn/shop/files/NinaLeeKewbelloJumpsuitEleanorMottram.jpg?v=1696062971>

**Diagnosis**: *Kewbellothea mottramia* is characterized by its olive-green-like color and ventral medial row of six circular vaguely green/gray buttons on the bodice.

**Etymology**: From *Mottram* + *-ia*.

**Specimens examined**: See holotype information.

<!-- Template generated with lct01tools and manually filled in by humans! -->
#### *Kewbellothea lavendula* {#sec-kewbellothea-lavendula}
<!-- FINALIZED 2026-04-11 -->
***Kewbellothea lavendula*** Lemuria, 2026; sp. nov.

**Holotype**: *Kewbello 67208.705* &mdash; Photograph.
3024&times;4032.
Ventral view. Subject's arms embedded in bilateral pockets. Taken outdoors during the day. Subject standing in shadow of building with plants in background. Hair terminates at roughly chin level; garment not obscured.
*Kewbellothea lavendula* wb. unknown.
&copy; unknown photographer, all rights reserved.

* **Page**: @kewbello1628
* **SHA2-256**: `0623aff976e9cecdc83b18a3a282202b3cc61e5300ecdc51e4b8ecb7977bedeb`
* **Raw image URLs**
  * **Original**: <https://www.ninalee.co.uk/cdn/shop/files/image_67208705.jpg?v=1696875452>
  * **IA**: <https://web.archive.org/web/20260405171751/https://www.ninalee.co.uk/cdn/shop/files/image_67208705.jpg?v=1696875452>

**Diagnosis**: *Kewbellothea lavendula* is characterized by its floral fabric, with a lavender background, multiple flowers, of which a red flower is highly prominent, with subtle cyan leaves.

**Etymology**: From Medieval Latin *lavendula* ("lavender"), from the lavender background of the fabric.

**Specimens examined**: See holotype information.

<!-- Template generated with lct01tools and manually filled in by humans! -->
#### *Kewbellothea rubera* {#sec-kewbellothea-rubera}
<!-- FINALIZED 2026-04-11 -->
***Kewbellothea rubera*** Lemuria, 2026; sp. nov.

**Holotype**: *Kewbello 27874.191* &mdash; Photograph.
2268&times;3024. EXIF metadata stripped.
Angled right ventral view. Subject's right arm on lateral end of waist. Hair positioned ventrally. Visibility of ventral medial button row significantly impeded by angle of bodice and pattern camouflage.
*Kewbellothea rubera* wb. unknown.
&copy;  or unknown photographer, all rights reserved.

* **Page**: @kewbello1628
* **SHA2-256**: `44a7d4f367d05f99db018a2a05fbf073886efca20d4bf1d38fe8d97e73e308a9`
* **Raw image URLs**
  * **Original**: <https://www.ninalee.co.uk/cdn/shop/files/20230910_191020_resized.jpg?v=1696875452>
  * **IA**: <https://web.archive.org/web/20260405171826/https://www.ninalee.co.uk/cdn/shop/files/20230910_191020_resized.jpg?v=1696875452>

**Diagnosis**: *Kewbellothea rubera* is characterized by a dorsal medial zipper that terminates at the bodice&ndash;skirt seam, a ventral medial button row, and a fabric with a red background with a leopard-like pattern of black and pink shapes, some of which superficially resemble human faces.

**Etymology**: From Latin *rubera*, corrupted form of *rubra*, feminine form of *ruber* ("red").

**Specimens examined**:

* Holotype.
* *Kewbello 27874.236* &mdash; Photograph.
2268&times;3024. EXIF metadata stripped.
Dorsal view. Subject's arms fully adducted. Hair positioned ventrally.
*Kewbellothea rubera* wb. unknown.
&copy; unknown photographer, all rights reserved.
  * **Page**: 
  * **SHA2-256**: `cd6b38f3dd7750cae473f395d6e6ae21807f636e8647c37c9873776988c5d808`
  * **Raw image URLs**
    * **Original**: <https://www.ninalee.co.uk/cdn/shop/files/20230910_190855_resized.jpg?v=1696875452>
    * **IA**: <https://web.archive.org/web/20260405171750/https://www.ninalee.co.uk/cdn/shop/files/20230910_190855_resized.jpg?v=1696875452>

<!-- Template generated with lct01tools and manually filled in by humans! -->
### *Kewbellothea* subg. *Ninae* {#sec-kewbellothea-subg-ninae}
<!-- FINALIZED 2026-04-11 -->
***Kewbellothea* subgenus *Ninae*** Lemuria, 2026

**Diagnosis**: Phylogenetically, *Kewbellothea* subg. *Ninae* is defined by having been created by Nina Chang-Smith.

**Etymology**: *Nina* + *-ae*.

<!-- replace taxon with the name of the rank! -->
**Type species**: *Kewbellothea autumna* (see @sec-kewbellothea-autumna)

<!-- Template generated with lct01tools and manually filled in by humans! -->
#### *Kewbellothea aquacolor* {#sec-kewbellothea-aquacolor}
<!-- FINALIZED 2026-04-11 -->
***Kewbellothea aquacolor*** Lemuria, 2026; sp. nov.

**Holotype**: ***Nina 90184.113*** &mdash; Photograph.
3000&times;4114.
*Kewbellothea aquacolor* wb. Nina, unknown.
&copy; Nina Chang-Smith or unknown photographer, all rights reserved.

* **Page**: @kewbello620
* **SHA2-256**: `aa9b9813b98b284c9aba1df3deaa3f0d1e430b499674060f1b047ce070eaad05`
* **Raw image URLs**
  * **Original**: <https://www.ninalee.co.uk/cdn/shop/files/Nina_Lee_Kewbello_with_sleeves_purple_background_v2.jpg?v=1722462174>
  * **IA**: <https://web.archive.org/web/20260405171750/https://www.ninalee.co.uk/cdn/shop/files/Nina_Lee_Kewbello_with_sleeves_purple_background_v2.jpg?v=1722462174>

**Diagnosis**: *Kewbellothea aquacolor* is characterized by its watercolor-like fabric, with a blue background and subtle purple shades; and a ventral medial button row of five circular blue buttons with four thread-holes.

**Etymology**: From Latin *aqua* ("water") + *color* ("color"); "watercolor", from the similarity of the fabric to watercolor.

**Specimens examined**:

* Holotype.
* *Nina 90184.148* &mdash;
Photograph. 3000&times;4114.
EXIF metadata stripped.
*Kewbellothea aquacolor* wb. Nina, unknown.
&copy; Nina Chang-Smith or unknown photographer, all rights reserved.
  * **Page**: 
  * **SHA2-256**: `47756822208f53a8ae585e460ae7036811ddf0ab88dc9db7347422cb5876e52f`
  * **Raw image URLs**
    * **Original**: <https://www.ninalee.co.uk/cdn/shop/files/Nina_Lee_Kewbello_with_sleeves_purple_background_c3.jpg>
    * **IA**: <https://web.archive.org/web/20260405171821/https://www.ninalee.co.uk/cdn/shop/files/Nina_Lee_Kewbello_with_sleeves_purple_background_c3.jpg>
* *Nina 90184.761* &mdash; Photograph.
3000&times;4114.
EXIF metadata stripped.
*Kewbellothea aquacolor* wb. Nina, unknown.
&copy; Nina Chang-Smith or unknown photographer, all rights reserved.
  * **Page**: 
  * **SHA2-256**: `a5676cb8be0f0537dd26f6c02a0bd046212af4b432990817a4e981e422bd0364`
  * **Raw image URLs**
    * **Original**: <https://www.ninalee.co.uk/cdn/shop/files/Nina_Lee_Kewbello_with_sleeves_back_view_purple_background_v2.jpg?v=1722462174>
    * **IA**: <https://web.archive.org/web/20260405171750/https://www.ninalee.co.uk/cdn/shop/files/Nina_Lee_Kewbello_with_sleeves_back_view_purple_background_v2.jpg?v=1722462174>
  
<!-- Template generated with lct01tools and manually filled in by humans! -->
#### *Kewbellothea autumna* {#sec-kewbellothea-autumna}
<!-- FINALIZED 2026-04-11 -->
***Kewbellothea autumna*** Lemuria, 2026; sp. nov.

**Holotype**: *Nina 90340.105* &mdash;
Photograph. 2400&times;2954.
EXIF metadata stripped.
*Kewbellothea autumna* wb. Nina, unknown.
&copy; Nina Chang-Smith or unknown photographer, all rights reserved.

* **Page**: @kewbello620
* **SHA2-256**: `274e7dbc7069f80d1cb77451eb2a5a1125578e73901f51e5cf09cee74751200f`
* **Raw image URLs**
  * **Original**: <https://www.ninalee.co.uk/cdn/shop/files/NinaLeeKewbelloJumpsuitautumnv1.jpg?v=1722462287>
  * **IA**: <https://web.archive.org/web/20260405171750/https://www.ninalee.co.uk/cdn/shop/files/NinaLeeKewbelloJumpsuitautumnv1.jpg?v=1722462287>

**Diagnosis**: *Kewbellothea autumna* is characterized by its maroon-background fabric with floral patterns. Orange, pink, and white flowers, with berry-like fruits, colored blue. No known correspondence to biological taxa.

**Etymology**: From Latin *autumna* ("autumn"), due to the autumn-like colors of the fabric and the holotype image.

**Specimens examined**: See holotype information.

### Genus *Kewisia* {#sec-kewisia}
<!-- FINALIZED 2026-04-11 -->
***Kewisia*** Lemuria, 2026

See @lemuria_taxonomy_2026

### *Kewisia* subg. *Ninae* {#sec-kewisia-subg-ninae}
<!-- FINALIZED 2026-04-11 -->
***Kewisia* subg. *Ninae*** Lemuria, 2026; subgen. nov.

**Diagnosis**: Phylogenetically, *Kewisia* subg. *Ninae* is defined by origin from Nina Chang-Smith or a close relative.

**Etymology**: *Nina* + *-ae*, feminine genitive suffix.

#### *Kewisia tropiki* {#sec-kewisia-tropiki}
<!-- FINALIZED 2026-04-11 -->
***Kewisia tropiki*** Lemuria, 2026; sp. nov.

**Holotype**: *Nina 2017.013.8377KT* &mdash; Photograph.
3543&times;5313.
EXIF metadata stripped.
Ventral view. Subject standing at angle. Hair positioned laterally and draping ventrally, right strap obscured.
*Kewisia tropiki* wb. Nina, c. 2017.
&copy; Nina Chang-Smith or unknown photographer, 2017, all rights reserved.

* **Page**: See @kew6_20
* **SHA2-256**: `42929bfbdf49b423201a3650623216e0cb08cbc41299a1c6f8b555f68ff5fea7`
* **Raw image URLs**:
  * **Original**: <https://www.ninalee.co.uk/cdn/shop/products/Kew-V2-Nina-1.jpg?v=1680151814>
  * **IA**: <https://web.archive.org/web/20230714101532/https://www.ninalee.co.uk/cdn/shop/products/Kew-V2-Nina-1.jpg?v=1680151814>

**Diagnosis**: *Kewisia tropiki* is characterized by a ventral medial button row of 15 circular two thread-hole buttons of a primarily ivory color with slight dark blue accents at random angles, and a consistent vertical threadline; and a fabric with a pink background with blue leaves, and red and purple flowers, the "Tropical Stems" fabric from Lady McElroy.

**Etymology**: 

**Specimens examined**:

* Holotype.
* *Kew 4557.234* (see @sec-image-specimens)

#### *Kewisia roseafolia* {#sec-kewisia-roseafolia}
<!-- FINALIZED 2026-04-11 -->
***Kewisia roseafolia*** Lemuria, 2026; sp. nov.

**Holotype**: *Nina 2017.013.8289KR* &mdash; Photograph.
1937&times;2657.
EXIF metadata stripped.
Angled ventral view. Subject's hair positioned laterally, obscuring her left strap.
*Kewisia roseafolia* wb. Nina, 2017.
&copy; Nina Chang-Smith or unknown photographer, 2017, all rights reserved.

* **Page**: See @kew6_20
* **SHA2-256**: `f4c34767bc2a237da8cfd304e052e3dfa7b97ee57dc0feba8116c11e00405f0a`
* **Raw image URLs**:
  * **Original**: <https://www.ninalee.co.uk/cdn/shop/products/Kew-Dress-V2-9.jpg?v=1680151814>
  * **IA**: <https://web.archive.org/web/20260326192109/https://www.ninalee.co.uk/cdn/shop/products/Kew-Dress-V2-9.jpg?v=1680151814>

**Diagnosis**: *Kewisia roseafolia* is characterized by a ventral medial button row of 15 circular two thread-hole buttons of a wooden color, and a fabric with stylized depictions of leaves in pink and white.

**Etymology**: From Latin *rosea*, feminine form of *roseus* "pink, rose-colored" + *folia*, pseudo-Latin feminine form of *folium* "leaf".

**Specimens examined**: See holotype information.

### Genus *Kewisicasa* {#sec-kewisicasa}
<!-- FINALIZED 2026-04-11 -->
***Kewisicasa*** Lemuria, 2026; gen. nov.

**Type species**: *Kewisicasa laria* (see @sec-kewisicasa-laria)

**Description**: Ventral medial row of 10 buttons. First buttonhole horizontal, others vertical. Seam across entire skirt between first and second buttons. Slight flare, no higher than ~20&deg;.^[For the purposes of defining flare, the silhouette of the fabric is measured, with the inferiormost end being considered north. The wearer is then assumed to be in the standard anatomical position with their head facing downwards; their left is considered 270&deg; and their right is considered 90&deg;.] Terminates roughly at knee-level. Slight drape at inferior end.

**Remarks**: Though we named the genus *Kewisicasa* in @lemuria_taxonomy_2026, we did not formally describe it. We now do so here.

#### *Kewisicasa laria* {#sec-kewisicasa-laria}
<!-- FINALIZED 2026-04-11 -->
***Kewisicasa laria*** Lemuria, 2026; sp. nov.

**Holotype**: *Kew 14201.147KL* &mdash; Photograph.
2067&times;2835.
EXIF metadata stripped.
Ventral view. White sleeveless shirt tucked underneath skirt.
*Kewisicasa laria* wb. Amy.C., 2017.
&copy; Nina Chang-Smith or unknown photographer, 2017, all rights reserved.

* **Page**: See @kew6_20
* **SHA2-256**: `00067336936823f5c556ec1e2a2796618d300d6becdc6b1d94b6f7b1ddacdf9d`
* **Raw image URLs**:
  * **Original**: <https://www.ninalee.co.uk/cdn/shop/products/Kew-Dress-V3-3.jpg?v=1680151814>
  * **IA**: <https://web.archive.org/web/20260327013520/https://www.ninalee.co.uk/cdn/shop/products/Kew-Dress-V3-3.jpg?v=1680151814>

**Diagnosis**: *Kewisicasa laria* is characterized by a ventral medial button row of 10 buttons, white background with two thread holes; and a sky blue fabric with seagull-like shapes.

**Etymology**: Pseudo-Latin feminine form of larus ("gull"), from the genus *Larus* Linnaeus, 1758.

**Specimens examined**:

* Holotype.
* ***Kew 14201.158KL*** &mdash; Photograph.
2067&times;2835.
EXIF metadata stripped.
Dorsal view. White sleeveless shirt tucked underneath skirt.
*Kewisicasa laria* wb. Amy.C., 2017.
&copy; Nina Chang-Smith or unknown photographer, 2017, all rights reserved.
  * **Page**: See @kew6_20
  * **SHA2-256**: `cb235a00a36a79798756de3885310b8469e53fe867fbf52a8fb3d9506b47f782`
  * **Raw image URLs**:
    * **Original**: <https://www.ninalee.co.uk/cdn/shop/products/Kew-Dress-V3-4.jpg?v=1680151814>
    * **IA**: <https://web.archive.org/web/20260327013518/https://www.ninalee.co.uk/cdn/shop/products/Kew-Dress-V3-4.jpg?v=1680151814>

### *Kewisicasa* subg. *Expansa* {#sec-kewisicasa-subg-expansa}
<!-- FINALIZED 2026-04-11 -->
***Kewisicasa* subg. *Expansa*** Lemuria, 2026; subgen. nov.

**Diagnosis**: Phylogenetically, *Kewisicasa* subg. *Expansa* is defined by origin from size 21 and above of the standalone straight skirt (*Kewisicasa*) variant of the Kew pattern.

**Etymology**: From Latin *expansa*, feminine form of *expansus* ("expanded"), referring to the larger size range.

#### *Kewisicasa jessae* {#sec-kewisicasa-jessae}
<!-- FINALIZED 2026-04-11 -->
***Kewisicasa jessae*** Lemuria, 2026; sp. nov.

**Holotype**: *Jess 29081.31.58KJ* &mdash; Photograph.
1440&times;1440.
EXIF metadata stripped.
Ventral view. Ventral medial button row unobscured. Hair terminates significantly superior to skirt. Visibility not obscured.
*Kewisicasa jessae* wb. Jess (`W/2026 F9`), unknown.
&copy; Unknown photographer, unknown, all rights reserved.

* **Page**: See @kew6_20
* **SHA2-256**: `9899938117bf4ffa79c03e6c6b80b4e998351f716eb010e74dbe1dca808f3125`
* **Raw image URLs**:
  * **Original**: <https://www.ninalee.co.uk/cdn/shop/products/Jess-Nina-Lee-Kew-Skirt-16-28.jpg?v=1677871695>
  * **IA**: <https://web.archive.org/web/20260330022036/https://www.ninalee.co.uk/cdn/shop/products/Jess-Nina-Lee-Kew-Skirt-16-28.jpg?v=1677871695>

**Diagnosis**: *Kewisicasa jessae* is characterized by a ventral medial button row of 11 buttons, white background and unknown black pattern, and an unknown amount of threadholes; and a plain magenta fabric. Slightly larger vertical gap between the first, second, and third buttons.

**Etymology**: *Jess* + *-ae*, feminine genitive suffix.

#### *Kewisicasa mandia* {#sec-kewisicasa-mandia}
<!-- FINALIZED 2026-04-11 -->
***Kewisicasa mandia*** Lemuria, 2026; sp. nov.

**Holotype**: *Mandy 210535.158.3903KM* &mdash; Photograph. 1658&times;2560. EXIF metadata stripped.
Ventral view. Subject looking upward. Drape of skirt obscures inferior portion of ventral medial button row. Arms extended outward.
*Kewisicasa mandia* wb. Mandy (`W/2026 F10`), unknown.
&copy; Unknown photographer, unknown, all rights reserved.

* **Page**: See @kew6_20
* **SHA2-256**: `459b5efb70c21f871d81205fbf51142631984ca4f8fdb03be464f10dc794442f`
* **Raw image URLs**:
  * **Original**: <https://www.ninalee.co.uk/cdn/shop/products/Mandy-Nina-Lee-Kew-Skirt-16-28-scaled.jpg?v=1677871695>
  * **IA**: <https://web.archive.org/web/20260330021938/https://www.ninalee.co.uk/cdn/shop/products/Mandy-Nina-Lee-Kew-Skirt-16-28-scaled.jpg?v=1677871695>

**Diagnosis**: *Kewisicasa mandia* is characterized by a ventral medial button row of 11 buttons, white with two thread-holes; and a green fabric with a grid of white lines.

**Etymology**: *Mandy* + *-ia*, feminine abstract noun suffix.

#### *Kewisicasa apprichia* {#sec-kewisicasa-apprichia}
<!-- FINALIZED 2026-04-11 -->
***Kewisicasa apprichia*** Lemuria, 2026; sp. nov.

**Holotype**: *Apprich 48183.493KA* &mdash; Photograph.
1200&times;1600.
EXIF metadata stripped.
Ventral view.
*Kewisicasa apprichia* wb. Emily.Ap., c. 2021.
&copy; Emily Apprich or unknown photographer, unknown year, all rights reserved.

* **Page**: @kewdressexpansion1628
* **SHA2-256**: `c5876e74a42dc028086fe963b1adacd5ef501ae0653418c4313a9bb09988ed28`
* **Raw image URLs**:
  * **Original**: <https://www.ninalee.co.uk/cdn/shop/products/Emily-Apprich-Kew-Expansion-pack-16-28-straight-skirt-10.jpg?v=1677871708>
  * **IA**: <https://web.archive.org/web/20260403143809/https://www.ninalee.co.uk/cdn/shop/products/Emily-Apprich-Kew-Expansion-pack-16-28-straight-skirt-10.jpg?v=1677871708>

**Diagnosis**: *Kewisicasa apprichia* is characterized by a ventral medial button row of 11 buttons, green and yellow with mixed colors, with a slightly larger gap between the first and second buttons; and a plain black fabric.

**Etymology**: *Apprich* + *-ia*.

**Specimens examined**: See holotype information.

#### *Kewisicasa argenta* {#sec-kewisicasa-argenta}
<!-- FINALIZED 2026-04-11 -->
***Kewisicasa argenta*** Lemuria, 2026; sp. nov.

**Holotype**: *Srebrenka 20180.118KA* &mdash; Photograph.
1920&times;2560.
EXIF metadata stripped.
Ventral view. Subject holding stick in left hand.
*Kewisicasa argenta* wb. Silverluna, c. 2021.
&copy; Srebrenka/Silverluna/sewsilverluna888 or unknown photographer, unknown year, all rights reserved.

* **Page**: @kewdressexpansion1628 and @ninaandsilverluna2021
* **SHA2-256**: `13463549148161ed83df081566e69ce421d0acaf9d54c9382ad2b2c767f48247`
* **Raw image URLs**:
  * **Original**: <https://www.ninalee.co.uk/cdn/shop/products/Srebrenka-Kapica-Kew-Expansion-pack-16-28-straight-skirt-1-scaled.jpg?v=1677871708>
  * **IA**: <https://web.archive.org/web/20260403143813/https://www.ninalee.co.uk/cdn/shop/products/Srebrenka-Kapica-Kew-Expansion-pack-16-28-straight-skirt-1-scaled.jpg?v=1677871708>

**Diagnosis**: *Kewisicasa argenta* is characterized by a ventral medial button row of 13 buttons, black with four thread holes, inconsistently spaced; and a navy-blue military camouflage-like pixel fabric, vaguely resembling ocean waves, with the small letters "OSRM" or "OSBM" scattered across the pattern. One of the most distinct shapes is one resembling the outline of Croatia's borders, in the lightest blue color.

**Remarks**:

* The shape of Croatia appearing on the fabric may be unintentional on the designer's part in designing the fabric, or on Srebrenka's part in choosing the fabric. This may be a form of pareidolia, further reinforced by our knowledge of Srebrenka's origin from the Balkans.
* Due to political sensitivities regarding the countries in the Balkans, we are unable to speculate on Srebrenka's home country beyond a general guess of "the Balkans".

**Etymology**: From Latin *argenta* ("silver"), from the first fragment of Silverluna's alias, *silver*.

**Specimens examined**: See holotype information.

### *Kewthea*
<!-- FINALIZED 2026-04-11 -->
***Kewthea*** Lemuria, 2026

See @lemuria_taxonomy_2026

### *Kewthea* subg. *Ninae*
<!-- FINALIZED 2026-04-11 -->
***Kewthea* subg. *Ninae*** Lemuria, 2026; subgen. nov.

**Diagnosis**: Phylogenetically, *Kewthea* subg. *Ninae* is defined by origin from Nina Chang-Smith or a close relative.

**Etymology**: *Nina* + *-ae*, feminine genitive suffix.

**Specimens examined**: See holotype information.

#### *Kewthea ruberabotonia* {#sec-kewthea-ruberabotonia}
<!-- FINALIZED 2026-04-11 -->
***Kewthea ruberabotonia*** Lemuria, 2026; sp. nov.

**Holotype**: *Kew 4109.187KR* &mdash; Photograph.
3543&times;5315.
EXIF metadata stripped.
Ventral view. Subject's hair positioned ventrally on her right.
*Kewthea ruberabotonia* wb. Amy.C. (`W/2026 F7`), c. 2017.
&copy; Nina Chang-Smith or unknown photographer, 2017, all rights reserved.

* **Page**: See @kew6_20
* **SHA2-256**: `4b13414afd28f3149ae852081a83dddc00f48b53e2263023726a7405762143ef`
* **Raw image URLs**:
  * **Original**: <https://www.ninalee.co.uk/cdn/shop/products/Kew-V1-Amy-close-up-1.jpg?v=1680151814>
  * **IA**: <https://web.archive.org/web/20230714160745/https://www.ninalee.co.uk/cdn/shop/products/Kew-V1-Amy-close-up-1.jpg?v=1680151814>

**Diagnosis**: *Kewthea ruberabotonia* is characterized by a ventral medial row of red buttons, plastic, with two thread holes, and a fabric with a white background and multiple unidentified plants.

**Etymology**: From pseudo-Latin *rubera*, corrupted form of *rubra*, feminine form of *ruber* ("red"). Also interpretable as *ruber* ("red") + *-a-* (epenthetic vowel added for euphony) + *botonia* ("button").

**Specimens examined**: See holotype information.

#### *Kewthea venetaflora* {#sec-kewthea-venetaflora}
<!-- FINALIZED 2026-04-11 -->
***Kewthea venetaflora*** Lemuria, 2026; sp. nov.

**Holotype**: *Kew 4109.124KV* &mdash; Photograph.
1937&times;2657.
EXIF metadata stripped.
Angled ventral view. Subject's hair positioned entirely dorsally. Subject facing to her right (relative to camera, from her perspective).
*Kewthea venetaflora* wb. Amy.C. (`W/2026 F7`), c. 2017.
&copy; Nina Chang-Smith or unknown photographer, 2017, all rights reserved.

* **Page**: See @kew6_20
* **SHA2-256**: `6d12a063eead31810dde4f7dbac040cf5e7fd1ba25d1fd5f601d21c2d4e3b378`
* **Raw image URLs**:
  * **Original**: <https://www.ninalee.co.uk/cdn/shop/products/Kew-Dress-V1-4.jpg?v=1680151814>
  * **IA**: <https://web.archive.org/web/20260326181258/https://www.ninalee.co.uk/cdn/shop/products/Kew-Dress-V1-4.jpg?v=1680151814>

**Etymology**: From Latin *veneta*, feminine form of *venetus* ("sky blue") + pseudo-Latin *flora* "flower", from Latin *Flora*, the goddess of flowers.

**Specimens examined**: See holotype information.

### *Kewthea* subg. *Expansa* {#sec-kewthea-subg-expansa}
<!-- FINALIZED 2026-04-11 -->
***Kewthea* subg. *Expansa*** Lemuria, 2026; subgen. nov.

**Diagnosis**: Phylogenetically, *Kewthea* subg. *Expansa* is defined by origin from size 21 and above of the tea dress (Kewthidae) variant of the Kew pattern.

**Etymology**: From Latin *expansa*, feminine form of *expansus* ("expanded"), referring to the larger size range.

#### *Kewthea hawkinsia* {#sec-kewthea-hawkinsia}
<!-- FINALIZED 2026-04-11 -->
***Kewthea hawkinsia*** Lemuria, 2026; sp. nov.

**Holotype**: *Laura 2023.001.1682KH* &mdash;
Photograph. 1871&times;2551.
EXIF metadata stripped.
Ventral view. Hair positioned ventrally, bilaterally obscuring certain parts of neckline. Skirt deliberately held out with hand.
*Kewthea hawkinsia* wb. Laura.Haw., 2023.
&copy; Laura Hawkins or unknown photographer, 2023, all rights reserved.

* **Page**: See @kew16_28
* **SHA2-256**: `e56fa1e776eb9a6cba4e98059778e9df903ab31613e39ad7c72422d4374dfe39`
* **Raw image URLs**
  * **Original**: <https://www.ninalee.co.uk/cdn/shop/products/Laura-Hawkins-Kew-Dress.jpg?v=1677871695>
  * **IA**: <https://web.archive.org/web/20260326050209/https://www.ninalee.co.uk/cdn/shop/products/Laura-Hawkins-Kew-Dress.jpg?v=1677871695>

**Diagnosis**: *K. hawkinsia* is characterized by a ventral medial button row of 15 heart-shaped two thread-hole buttons, and a fabric with a light white&ndash;pink background and a stylized red flower with two petals and black dots scattered in a roughly rectangular shape with curved edges.

**Etymology**: From *Hawkins* + *-ia*, feminine abstract noun suffix.

**Specimens examined**: See holotype information.

#### *Kewthea caledonia* {#sec-kewthea-caledonia}
<!-- FINALIZED 2026-04-11 -->
***Kewthea caledonia*** Lemuria, 2026; sp. nov.

**Holotype**: *Emma 2023.001.1402KC* &mdash;
Photograph. 1440&times;2560.
EXIF metadata stripped.
Ventral view. Indoors. Hair positioned ventrally, bilaterally obscuring certain parts of neckline.
*Kewthea caledonia* wb. Emma (`W/2026 F5`), c. 2023.
&copy; Emma or unknown photographer, c. 2023, all rights reserved.

* **Page**: See @kew16_28
* **SHA2-256**: `4e650f4804476216e169e757f5eecf9a9fb87279ebda2e477b8bbc0b5e59644f`
* **Raw image URLs**:
  * **Original**: <https://www.ninalee.co.uk/cdn/shop/products/Sew-Do-It-Emma-Nina-Lee-Kew-Dress-16-28-scaled.jpg?v=1677871695>
  * **IA**: <https://web.archive.org/web/20260326051449/https://www.ninalee.co.uk/cdn/shop/products/Sew-Do-It-Emma-Nina-Lee-Kew-Dress-16-28-scaled.jpg?v=1677871695>

**Diagnosis**: *K. caledonia* is characterized by a ventral medial button row of ~15 small buttons.^[Image resolution insufficient to identify buttons.], and a fabric with a dark-blue background and numerous variably-sized sky blue, purple, and pale bright orange dots scattered at random.

**Etymology**: From Latin *Caledonia* ("Scotland"), from Emma's location.

**Specimens examined**: See holotype information.

#### *Kewthea glaciesedulis* {#sec-kewthea-glaciesedulis}
<!-- FINALIZED 2026-04-11 -->
***Kewthea glaciesedulis*** Lemuria, 2026; sp. nov.

**Holotype**: *Laura 20710.583KG* &mdash;
Photograph. 2560&times;2560.
EXIF metadata stripped.
Ventral view. Outdoors. Hair positioned ventrally, bilaterally obscuring certain parts of neckline. In left hand, subject holding object similar to "ice cream cone"; with a conical cardboard material representing the "cone" and a ball of yarn representing the "ice cream".
*Kewthea glaciesedulis* wb. Laura.Haw., c. 2023.
&copy; Laura Hawkins or unknown photographer, c. 2023, all rights reserved.

* **Page**: See @kewdressexpansion1628
* **SHA2-256**: `adeab545bfd020f27e3900970327930d25ffb1c51b319bfe752cc209d5d41872`
* **Raw image URLs**:
  * **Original**: <https://www.ninalee.co.uk/cdn/shop/products/Laura-Hawkins-Specky-Seamstress-Kew-Expansion-16-28-gathered-skirt-1-scaled.jpg?v=1677871708>
  * **IA**: <https://web.archive.org/web/20260405161421/https://www.ninalee.co.uk/cdn/shop/products/Laura-Hawkins-Specky-Seamstress-Kew-Expansion-16-28-gathered-skirt-1-scaled.jpg?v=1677871708>

**Diagnosis**: *K. glaciesedulis* is characterized by a ventral medial button row of 15 white buttons; and a fabric with a white background with a pattern of ice cream cones; consisting of cyan-colored ice cream in a cone drawn with black lines.

**Etymology**: From Latin *glacies* ("ice") + *edulis* ("edible"), literally "edible ice". Translation sourced from Wiktionary.

**Specimens examined**: See holotype information.

#### *Kewthea eleanorae* {#sec-kewthea-eleanorae}
<!-- FINALIZED 2026-04-11 -->
***Kewthea eleanorae*** Lemuria, 2026; sp. nov.

**Holotype**: *Eleanor 2023.001.8404KE* &mdash;
Photograph. 1440&times;2560.
EXIF metadata stripped.
*Kewthea eleanorae* wb. Eleanor (`W/2026 F3`), c. 2023.
&copy; Eleanor or unknown photographer, c. 2023, all rights reserved.

* **Page**: See @kew16_28
* **SHA2-256**: `e15a799d0f7b20bc03da95bfcf0cf0f8fed33443fa70cda44bbf35bba2265bdd`
* **Raw image URLs**:
  * **Original**: <https://www.ninalee.co.uk/cdn/shop/products/Eleanor-Nina-Lee-Kew-Dress-16-28-scaled.jpg?v=1677871695>
  * **IA**: <https://web.archive.org/web/20260326051053/https://www.ninalee.co.uk/cdn/shop/products/Eleanor-Nina-Lee-Kew-Dress-16-28-scaled.jpg?v=1677871695>

**Diagnosis**: *K. eleanorae* is characterized by a ventral medial button row of 10 circular buttons with no thread holes, four on the bodice and six on the skirt; and a plain dark blue fabric.

**Etymology**: From *Eleanor* + *-ae*, feminine genitive suffix.

**Specimens examined**: See holotype information.

#### *Kewthea lauraflora* {#sec-kewthea-lauraflora}
<!-- FINALIZED 2026-04-11 -->
***Kewthea lauraflora*** Lemuria, 2026; sp. nov.

**Holotype**: *Laura 2023.001.4901KL* &mdash;
Photograph. 1920&times;2560.
EXIF metadata stripped.
*Kewthea lauraflora* wb. Laura (`W/2026 F4`), c. 2023.
&copy; Laura or unknown photographer, c. 2023, all rights reserved.

* **Page**: See @kew16_28
* **SHA2-256**: `e03d4374644fb22f63d97ccc4d5ca523f35889c85666bda316040e7174ec3404`
* **Raw image URLs**:
  * **Original**: <https://www.ninalee.co.uk/cdn/shop/products/Laura-Nina-Lee-Kew-Dress-16-28-scaled.jpg>
  * **IA**: <https://web.archive.org/web/20260326192448/https://www.ninalee.co.uk/cdn/shop/products/Laura-Nina-Lee-Kew-Dress-16-28-scaled.jpg>

**Diagnosis**: *K. lauraflora* is characterized by a ventral medial button row of 13 circular purple buttons with a primarily purple floral pattern.

**Etymology**: From *Laura* + pseudo-Latin *flora*, to distinguish from *Kewthea hawkinsia* wb. Laura.Haw., from Latin *Flora*, the goddess of flowers.

**Specimens examined**: See holotype information.

```{=latex}
\newpage
\begin{multicols}{2}
```

## General remarks
At least two distinct persons appear in the official product photography for @kew6_20, with the exception of pattern testers. We were able to identify the first person as Nina Chang-Smith herself.

The second person, the one wearing *Kewisicasa laria*, was slightly harder to identify; but we believe the person's name to be Amy Chang, based on (1) the filename for *Kew 4109.187KR* being "Kew-V1-Amy-close-up-1.jpg", and (2) the presence of the name *Amy Chang* on seating chart signage for Chang-Smith's June 2019 wedding [@changsmith2020, ninth image on page].

We were able to infer Silverluna's name as being *Srebrenka Kapica* based on image filenames.

## Appendix

### Person abbreviations
<!-- CONCERN 3: Ensure we cite all usage of person abbrs and that we listed all the new ones here -->
<!-- Proofreading completed, no abbrs missed, but I did forget to fill in the year and almost forgot to write unknown in an empty field. -->
The abbreviations **Nina** for Nina Chang-Smith and **Lemuria** for Lemuria have been defined in @lemuria_taxonomy_2026.

In this paper, we establish the new person abbreviations:

* **Laura.Haw.** &mdash; Laura Hawkins (`W/2026 F6`), pattern tester for the Kew expansion pack
* **Amy.C.** &mdash; Amy Chang (`W/2026 F7`), relative of Nina Chang-Smith
* **Silverluna** &mdash; Srebrenka Kapica (Instagram: &commat;[sewsilverluna888](https://instagram.com/sewsilverluna888); `W/2026 G1`), sewist from Europe (nationality unknown; possibly the Balkans)
* **Emily.Ap.** &mdash; Emily Apprich (`W/2026 G2`), pattern tester.

We establish the new alphanumeric designations:

* **Eleanor** (`W/2026 F3`), wearer of *Kewthea eleanorae*
* **Laura** (`W/2026 F4`), wearer of *Kewthea lauraflora*
* **Emma** (`W/2026 F5`), wearer of *Kewthea caledonia*
* **Jess** (`W/2026 F9`), wearer of *Kewisicasa jessae*
* **Mandy** (`W/2026 F10`), wearer of *Kewisicasa mandia*

### Image specimens {#sec-image-specimens}
We used the following image specimen identifiers:

<!-- CONCERN 2: Ensure we listed all the image identifiers -->
<!-- I forgot Apprich and Srebrenka, but at least they're here now. Also the 4557.234 alt for Kew 9018.1728 -->
* *Apprich 48183.493KA*
* *Eleanor 2023.001.8404KE*
* *Emma 2023.001.1402KC*
* *Jess 29081.31.58KJ*
* *Kew 14201.147KL*
* *Kew 14201.158KL*
* *Kew 4109.124KV*
* *Kew 4109.187KR*
* *Kew 74024.100HR*
* *Kew 9018.1728* (*Kew 4557.234*)
* *Kewbello 27874.191*
* *Kewbello 27874.236*
* *Kewbello 67208.705*
* *Laura 2023.001.1682KH*
* *Laura 2023.001.4901KL*
* *Laura 20710.583KG*
* *Mandy 210535.158.3903KM*
* *Mottram 4958.194*
* *Nina 2017.013.8289KR*
* *Nina 2017.013.8377KT*
* *Nina 90184.113*
* *Nina 90184.148*
* *Nina 90184.761*
* *Nina 90340.105*
* *Nina 90381.248*
* *Nina 90381.276*
* *Nina 90387.475*
* *Nina 90387.478*
* *Srebrenka 20180.118KA*

```{=latex}
\end{multicols}
```

#### New image specimens
These image specimens do not correspond to one singular taxon.

* *Kew 9018.1728* 
(a.k.a. *Kew 4557.234*) &mdash; Photograph.
3361&times;4618.
EXIF metadata stripped.
On left, Amy Chang, standing, facing camera, hair positioned laterally, partial obscuration of straps; on right, Nina Chang-Smith, facing camera, hair positioned laterally, straps minimally obscured. Both standing at angles relative to camera. Inferiormost button of *Helikewisia amyboria* unfastened.
Left: *Helikewisia amyboria* wb. Amy.C, 2017; right: *Kewisia tropiki* wb. Nina, 2017;
&copy; Nina Chang-Smith or unknown photographer, c. 2017, all rights reserved.
  * **Page**: See @kew6_20
  * **SHA2-256**: `2cf4fe38ca4e664c8a05a60ca0b3b203d7b672f6988e530f0186e724938ae614`
  * **Raw image URLs**:
    * **Original**: <https://www.ninalee.co.uk/cdn/shop/products/NinaLeeKewDressversion1.jpg?v=1680151814>
    * **IA**: <https://web.archive.org/web/20260326190410/https://www.ninalee.co.uk/cdn/shop/products/NinaLeeKewDressversion1.jpg?v=1680151814>

```{=latex}
\newpage
\begin{multicols}{2}
```

### Acknowledgements
We used R; specifically, `ggtree`, to render tree figures. For information on `ggtree`, see @yuetal2017.

We thank Nina Lee for her amazing patterns that help bolster a culture of home sewing and advance the slow fashion movement. We thank all the sewists and the sources we have cited for documenting their projects in intricate detail.

We thank the people of the Coffee Shop on [4d2.org](https://4d2.org), where our lead author has posted fragments of the paper time and time again, for being absolutely wonderful people, and being an extra set of eyes to keep errors shallow under Linus's law; and we thank Sarah, the operator of 4d2, for fostering such a wonderful space.

### Data availability
Supplementary data, such as the .yml file containing structured data for *Kewbellothea*; and the raw standalone Newick tree, are made available on Zenodo.

### Information
*Lemuria's (Informal) Journal of Clothing Taxonomy* is the gray literature journal of the First Lemurian Clothing Taxonomy, a system by Lemuria to assign Latin names to dresses using biological methods. The author, known mononymically as just Lemuria, is an Filipino programmer and independent gray literature researcher from Manila.

**Disclaimer**: *Lemuria's (Informal) Journal of Clothing Taxonomy* is a non-peer-reviewed, single-author, citizen science/gray literature publication with no institutional backing.

Publisher article ID: 2026.0008 (intranet: `L78.1098/lict2026.0008`, not for external use)

DOI: [`10.5281/zenodo.19466565`](https://doi.org/10.5281/zenodo.19466565) (provided by Zenodo)

At publication, the journal did not have a DOI prefix.

Work began on the paper on 2026-03-26 and entered the proofreading and minor revision stage on 2026-04-09. It was published on 2026-04-11.

* Visit us at: <https://lct01.lemuria.ph>
* Version control: <https://github.com/a-random-lemurian/lct01.lemuria.ph>
* Zenodo: <https://zenodo.org/communities/lct01>

&copy; Lemuria 2026. All original text and image content by Lemuria is licensed under CC BY-SA 4.0, unless explicitly noted. Linked images and other content are &copy; their respective owners or copyright holders.

### References

::: {#refs}
:::

```{=latex}
\end{multicols}
```
