---
title: "An inordinate fondness for Silversaga and her patterns: a monograph"
author:
  name: Lemuria
  affiliation:
    - name: Independent researcher; Manila, Philippines
  email: lemuria@lemuria.ph
license: CC BY-SA
journal:
  title: "Lemuria's (Informal) Journal of Clothing Taxonomy"
date: 2026-04-07
lang: en
execute: 
  freeze: true
# publisher-id: "lict2026.0006"
abstract: |
  Jessica Silversaga is a Swedish pattern designer, photographer, and sewist, the owner of Silversaga Patterns, a slow fashion RTW-turned sewing pattern label. In this monograph, we comprehensively describe N species of garments made from Silversaga patterns, across 2 orders, 15 families, N genera, and N species, publishing and refining the early private research conducted on the Eleonora dresses in early 2026.
bibliography: silversaga.bib
number-sections: true
citation:
  author: Lemuria
  # citation-key: lemuria_kew_2026
  title: "An inordinate fondness for Silversaga and her patterns: a monograph"
  original-date: 2026-04-07
  publisher: Lemuria
  # article-id: lict2026.0006
  publisher-place: Philippines
filters:
  - hash.lua
format:
  html:
    format-links: false
    # other-links:
    #   - text: PDF
    #     href: https://static.lemuria.ph/lct01/pdf/2026/2026.0006_gunnelaurentia_johnsonia.pdf
    #     icon: file-pdf
  aft-pdf:
    toc: true
    toc-depth: 6
    include-in-header:
      text: |
        \usepackage{forest}
        \usepackage{seqsplit}
keywords: silversaga, eleonora, sleeveless eleonora, silversaga patterns, sewing patterns, clothing taxonomy
---

```{=latex}
\begin{multicols}{2}
```

# Background
## Jessica Silversaga {#sec-j-silversaga}
Jessica Silversaga (<https://silversagapatterns.com>; Instagram: &commat;[`silversagapatterns`{.hash}](https://instagram.com/silversagapatterns); personal Instagram: &commat;[`jessicasilversaga`{.hash}](https://instagram.com/jessicasilversaga)) is a Swedish photographer, pattern designer, and sewist.

In high school, she took journalism & photography; and in 2005, she graduated with a Bachelor of Photography from the Mid Sweden University.

She became interested in sewing after taking a beginner's sewing class. Most patterns and RTW garments available to her were incompatible with her petite frame and smaller cup size. In her late 20s, Silversaga began taking pattern drafting classes in Stockholm.

In late 2018, she launched the slow fashion RTW label Silversaga. Many of the patterns now available through Silversaga Patterns were sold RTW during this period. She designed seven collections on a seasonal schedule; autumn/winter (A/W) 2019, 2021, and 2022; and summer/spring (S/S) 2020, 2021, 2022, and 2023. The dresses were either preproduced in small batches, or made-to-order by an Estonian atelier.

Due to the COVID-19 pandemic, in 2023, she transitioned the business to a pattern label, ceasing sales of RTW garments and switching to selling PDF patterns.

Simon, Jessica's fiancé, joined the company in 2024.

Silversaga's history is split into two primary periods; the slow fashion period (2018&ndash;2023) and pattern period (2023&ndash;present).

### Online presence
Jessica's online presence dates to the early 2000s. WHOIS records show that the domain `silversaga.se` was registered on December 9, 2004. The earliest Wayback Machine captures for her website, <https://silversaga.se> date to 2006, when it was used as a portfolio website for her photography. Based on snapshots, which the Archive took at seemingly random non-consistent intervals, throughout the 2010s she kept a blog in both English and Swedish on the website.

It became an e-commerce website c. 2020, two years into the launch of Silversaga, and with the start of the pattern period, the `silversaga.se` domain became a redirect to <https://silversagapatterns.com>. The delay is likely due to Silversaga's early commercial activities having taken place on Etsy.

Silversaga's online store uses software from Shopify, a Canadian e-commerce company.

The Shopify instances on both `silversaga.se` and `silversagapatterns.com` are the same. As a result, many holotypes from the RTW period survive to 2026. Though the Internet Archive was unable to fully cover all of `silversaga.se`'s product pages, the images in question are still accessible through Shopify's CDN, and can be archived. An example of these retrieved holotypes is *Silversaga 2022.58*, featuring *Argenteleonora candiga natalia* (<https://cdn.shopify.com/s/files/1/0562/9375/2969/products/SilversagaSS2022_58.jpg?v=1649342524>; see @sec-argenteleonora-candiga),

### Patterns
Jessica's total pattern repertoire is around ~200, as of January 2026 [@silversaga_helpmename].

As of April 2026, only 14 of these patterns are available for purchase through Silversaga Patterns. In alphabetical order, they are the
Alma,
Amelie,
Celeste,
Celine,
Chloe,
Clara,
Eleonora,
Ella,
Elsa,
Emma,
Francesca,
Juliette,
Mina,
and Ophelia.

In 2025, the five most popular patterns were the
Celine,
Chloe,
Eleonora,
Amelie,
and Ella.

These patterns are sold entirely as PDFs with English-language instructions. Patterns are available in sizes EU 34&ndash;54 UK 6&ndash;26, and US 2&ndash;24.

Many of these patterns date back to the RTW period, while some, such as the Celeste (April 2026), were new when work began on the monograph.

The Eleonora comes in two primary variants, sold as two separate patterns; a sleeved variant, known simply as the Eleonora; and a sleeveless variant, sold as the Sleeveless Eleonora.
We will refer to both as the sleeved and sleeveless Eleonora respectively, for clarity; we use the term Eleonora itself to refer to both patterns collectively.

Jessica tests her patterns in one to three rounds, with a total of anywhere from 40 to 70 testers, ranging from EU sizes 34 to 54. [@silversagafaq]

Based on these figures, we estimate at least 600&ndash;1,050 extant species across the 15 families. For comparison, the LCT-01 had ~300 species across ~70 genera as of the last count conducted in February.

Silversaga's aesthetic is variously described as "romantic minimalism" [@rainey2025], <!-- TODO: gather more reviews of what people call Silversaga, please... -->

### Terminology
We will be referring to Jessica Silversaga by her first name throughout the monograph, to better distinguish her from her company, Silversaga Patterns. She also has the person abbreviation *J.Silversaga* (see @sec-person-abbrs).

## Pattern testers
In this section, we include brief biographies of some of Silversaga's pattern testers. For person abbreviations, see @sec-person-abbr.

Pattern testers' names were inferred by reading filenames and browsing Instagram, as elaborated on in @sec-materials-and-methods.

<!-- sort these people by last name -->

<!--
Lynne is the person's middle name,
Routamaa is the last name but this is less publicly visible
so we sort by B
(and even though we publish the last name,
the title is still Bethany Lynne, so sort by B still)
-->
### Bethany Lynne
**Bethany Lynne Routamaa** (<https://www.bethanylynnemakes.com/about/>; Instagram: &commat;[`bethanylynne_makes`{.hash}](https://instagram.com/bethanylynne_makes)) is an American sewist from east Texas. She learned sewing and knitting from her mother and grandmother. Though her earliest interests were in painting, she has since diversified to other creative pursuits such as knitting, crocheting, graphic design, quilting, and most taxonomically relevant, sewing. Her earliest me-made garments date back to 2021.

Bethany has now designed her own patterns; such as the Agnes sweater, Homebody apron, and numerous backpacks, sling bags, and tote bags.

During the early pattern period, Bethany won a copy of five patterns from Silversaga (the entire published collection at the time), which led to the start of her interest in Silversaga. Bethany typically makes garments in EU size 36 [@bethany2025].

Her last name, Routamaa, is attested in pattern tester filenames.

<!-- TODO: REPLACE THIS PLACEHOLDER! -->
**Wearer of**: 9 spp.;
Genus *Argenteleonora*: *bethanae* (@sec-argenteleonora-bethanae); 

### Lauren Johnson
**Lauren Johnson** (<https://bouquetbylauren.com/about/>; Instagram: &commat;[`justlaurenjohnson`{.hash}](https://instagram.com/justlaurenjohnson)) is an American sewist and YouTuber from Little Rock, Arkansas. She runs the Bouquet Pattern Co. First covered in the LCT-01 in @lemuria_gunnelaurentia_2026, a description of *Gunnelaurentia johnsonia* Lemuria, 2026. 

**Wearer of**: 1 sp.;
*Celina laurentia* (@sec-celina-laurentia)

### Madeleine Salisbury
**Madeleine Claire Salisbury** (Instagram: &commat;[`made_by_madeleine.claire`{.hash}](https://instagram.com/made_by_madeleine.claire)) is an American sewist, originally from New York, now living in Prague, Czech Republic. Salisbury herself was discovered as part of yet-to-be-published taxonomic work on other patterns; specifically the Traveller coat by Bella Loves Patterns.

Salisbury is one of Jessica's pattern testers; she has tested the Eleonora [@salisbury2024_eleonora; @salisbury2024_eleonora2], the Juliette [@salisbury2024]

<!-- TODO: REPLACE THIS PLACEHOLDER! -->
**Wearer of**: N spp.;
Genus *Argenteleonora*: *madeleinae* (@sec-argenteleonora-madeleinae), *madeleinatra* (@sec-argenteleonora-madeleinatra);
Genus *Julietta*: *madeleinae* (@sec-julietta-madeleinae)

## Taxonomic remarks
The hybrid RTW&ndash;home-sewn nature of the taxonomic record of Silversaga garments leads to a taxonomically interesting situation for the LCT-01.

Silversaga was historically a slow fashion RTW label, as explained in @sec-j-silversaga. After the COVID-19 pandemic led to the label transitioning to patterns, the first home-sewn Silversaga garments arose.

In the simplest of cases, RTW taxonomy typically maps the design, colorway, and wearer to the genus, species, and subspecies respectively; while sewing patterns map the design, option (or view), and individual sewist to the family, genus, and species [@lemuria_general_2026].

The most reliable morphological character identifying Silversaga garment taxa of RTW origin is the presence of a label reading "Silversaga" on the superior medial point of the garment's dorsal interior surface.

As with Nina Lee's Kew dress, extensively taxonomized in prior monographs published in the *Journal*, some of these patterns are classified polyphyletically, due to the dispersion of their morphological diversity across the higher-level taxa of the LCT-01.

### Varieties and forms
<!-- 
maybe the LCT-01 will have a formal code by the time this monograph is finished. who knows, really...
-->

The LCT-01 makes significant use of infrageneric and subspecific taxa, especially in these monographs. We use the subgenus, section, and series, variety, and form in their botanical sense. RTW instances of Silversaga taxa use subspecies. We use the zoological convention for subspecies; unlike botany, we do not use the *subsp.* or *ssp.* particle.

The variety corresponds to individual, often irreversible small variations in the dress, such as fabric modification (e.g. *Argenteleonora bethanae*, @sec-argenteleonora-bethanae; var. *athea* and var. *brunalana*), trimming, or alterations.

The form corresponds to the positioning of the dress on the human body or the status of easily reversible configurations (e.g. button fastening, tied or untied ribbons, or sleeves pulled downward, lateral to the upper arm).

The LCT-01 makes use of the "blessed form" doctrine; for example, a dress such as the Clara can be worn on or off-shoulder. If it were worn off-shoulder, it would be considered part of the class Umerostentida, subclass Alourida; while if it were worn on-shoulder,  Designer intent is that the sleeves are worn on the shoulder, though the product page explicitly acknowledges the off-shoulder configuration (and notes that it is breastfeeding-friendly).

### Taxonomic history
Our lead author discovered Silversaga through the American sewist Madeleine Salisbury (Instagram: &commat;[made_by_madeleine.claire](https://instagram.com/made_by_madeleine.claire)).

During the early taxonomization of Jessica's patterns, the LCT-01 began using infrageneric taxa; ranks below genus but above species, such as subgenera and sections, due to the increasing awkwardness of incorporating an increasing amount of characters in the genus name itself. 

<!-- ### Scope of the monograph -->
Originally, we intended for this paper to only cover the Eleonora dress (Argenteleonoridae) and its sleeveless variant (Heleonoridae); but later decided to expand to the other garments within Silversaga's repertoire.

<!--
if we can publish this by the start of Me Made May
as an extra nod to the sewing pattern community......
....

However, we exclude the Celeste pattern, as its 16 views and 12 pattern hacks included with the pattern lead to a lower bound for 192 taxa, over 2.5&times; the number of genera in the LCT-01 as last counted c. February 2026, ~75. -->

## Materials and methods {#sec-materials-and-methods}
### Equipment and software
The author conducted his research on a computer running Ubuntu 24.04, with the XFCE desktop environment. He used the SHA2-256 algorithms to compute the cryptographic hashes of the photographic specimens he examined for species descriptions. He used Firefox 139.0.4. His monitor is a 55.8 cm (22 in) wide, 30.48 cm (12 in) tall, 63.5 cm (25 in) diagonal monitor, the NVISION S2515-B 25" IPS with a 100Hz refresh rate. He is not colorblind. He is near sighted and wears glasses.

### Images
As our lead author had no Instagram account, he used Imginn, an online service that allows Instagram to be viewed without an account.

Images were hashed with the SHA2-256 algorithms, using the `sha256sum` utility on his system. The versions of the `sha256sum` and `openssl` utilities on his system at the time of the paper are given in @fig-sha256sum.

Specimens were collected from Silversaga Patterns' website (<https://silversagapatterns.com>); with a focus on the pattern tester galleries. The Silversaga Patterns website uses Shopify as its underlying platform and image storage; EXIF metadata removal is likely consistent with internal Shopify server-side upload processing code.

The images were of exceptionally high quality; resolutions as high as 4000&times;2667 were collected. The majority of the images were in JPG format; some images were stored in the HEIC format.

To check EXIF metadata, he used ExifTool version 12.76.

We inferred the approximate dates of some pattern releases, with maximum confidence in the year and month, with absolutely none on the day, by retrieving sitemaps from the Silversaga website, which we include in supplementary data.

<!--
may need a major update if lct01-notes is further
refined during the Silversaga monograph

### `lct01-notes`
During work on this paper, the author created a new tool that automatically generates Quarto template text from structured YAML data. This allows the data to exist in a structured format for future processing with other systems, and further improves standardization. Descriptions and remarks remain human-written; with less administrative and menial work comes the opportunity for more creative work.

A paper dedicated solely to this software has not been started, but may be authored someday. YAML files used to generate the template text are provided with the paper. -->

```{=latex}
\end{multicols}
```

::: {#fig-sha256sum}
```
$ sha256sum --version
sha256sum (GNU coreutils) 9.4
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Ulrich Drepper, Scott Miller, and David Madore.
$ openssl --version
OpenSSL 3.5.0 8 Apr 2025 (Library: OpenSSL 3.5.0 8 Apr 2025)
$ sha256sum /usr/bin/sha256sum /usr/bin/openssl
f293048f656688883ee919eb3f4b12926aaa13362de0eb6e3b5716b915b18b35  /usr/bin/sha256sum
724acbe911513d13f52bae0b8969b20336cd8618fc67898a6bf7847bf1a270ad  /usr/bin/openssl
```

A hash of the sha256sum and openssl utilities on the lead author's computer.
:::

<!--
(((((((Heleonoridae[&&NHX:subtree_root=yes],Helargemmidae[&&NHX:subtree_root=yes],Helarchloidae[&&NHX:subtree_root=yes])Helargenta)Helistola)Scapamanica)Scapunatoria,(((((Argenteleonoridae[&&NHX:subtree_root=yes],
Argenkamellidae[&&NHX:subtree_root=yes])Sueciargenta)Kampylilaimosida)Quaracomorpha,(Argentellidae[&&NHX:subtree_root=yes])Vecostola,((Almidae[&&NHX:subtree_root=yes],Juliettidae[&&NHX:subtree_root=yes],Argenclaridae[&&NHX:subtree_root=yes])Isargenta)Isotrapezia)
Manubristenta))Abtruncusa)Vestimentia)

----
incertae sedis 1

Elsa    -- Argelsidae
Ophelia -- Ophelidae


-- this pattern is going to be
-- a nightmare to taxonomize.
--
-- 16 style views. 12 pattern hacks.
-- 192 cells on the punnett square.
--
Celeste -- Celestia? Celestistola? (order)
           Celestidae (family)

----
incertae sedis 2

Phylum Scapunatoria
Subphylum Scapamanica
Class Camisola
Order Argentisola
Family Francescidae

Francesca  -- Francescidae

----
incertae sedis 3

Amelie    -- Amelidae

-->

```{=latex}
\newpage
```

### Trees
```{r}
#| results: asis
#| fig-show: asis
#| message: false

library(treeio)
library(ggtree)
library(ggplot2)
library(ggtreeExtra)
library(dplyr)
library(ggtext)
library(knitr)

text <- "((((((((Heleonora[&&NHX:rank=genus])Heleonoridae[&&NHX:subtree_root=yes],(Helargemmia[&&NHX:rank=genus])Helargemmidae[&&NHX:subtree_root=yes],(Helarchoia[&&NHX:rank=genus])Helarchloidae[&&NHX:subtree_root=yes])Helargenta)Helistola,(((Francesca[&&NHX:rank=genus])Francescidae[&&NHX:subtree_root=yes])Argentisola)Camisola)Scapamanica)Scapunatoria,(((((((Argenteleonora_ariae,Argenteleonora_felicitae,Argenteleonora_madalinae,Argenteleonora_madeleinae,Argenteleonora_madeleinatra,Argenteleonora_mantorae,Argenteleonora_manuelae,Argenteleonora_martae,Argenteleonora_rubra,Argenteleonora_stephania,Argenteleonora_thea,Argenteleonora_veneta)Argenteleonora_subg._Shira,((Argenteleonora_annettae)Argenteleonora_sect._Unilastica,(Argenteleonora_bethanae,Argenteleonora_patriciae,Argenteleonora_katiae)Argenteleonora_sect._Duolastica)Argenteleonora_subg._Elastica)Argenteleonora[&&NHX:rank=genus])Argenteleonoridae[&&NHX:subtree_root=yes],(Argenkamella[&&NHX:rank=genus])Argenkamellidae[&&NHX:subtree_root=yes])Sueciargenta)Kampylilaimosida)Quaracomorpha,((Argentella[&&NHX:rank=genus])Argentellidae[&&NHX:subtree_root=yes])Vecostola,(((Almargenta[&&NHX:rank=genus])Almidae[&&NHX:subtree_root=yes],(Julietta[&&NHX:rank=genus])Juliettidae[&&NHX:subtree_root=yes],(Argenclara[&&NHX:rank=genus])Argenclaridae[&&NHX:subtree_root=yes])Isargenta)Isotrapezia)Manubristenta)Abtruncusa)Vestimentia);"

tree <- read.nhx(textConnection(text))

subtree_nodes <- tree@data %>%
  filter(subtree_root == "yes") %>%
  pull(node)

p <- ggtree(tree)

for (n in subtree_nodes) p <- collapse(p, n) + geom_point2(aes(subset=(node==!!n)), shape = 23, size=5, fill='red')

rootTree <- p + geom_tiplab(size = 3) +
  geom_richtext(
    aes(label = label),
    data = td_filter(!isTip),
    size = 2, na.rm = TRUE,
    fill = 'lightblue', label.color = 'white'
  ) + vexpand(1)

fig_height <- function(tr) max(3, min(length(tr@phylo$tip.label) * 0.25, 12))

plots <- list(
  list(p = rootTree, w = 12, h = 8, label = "Overview")
)

format_node_label <- function(label, rank) {
  if (!is.na(rank) && rank == "genus") {
    return(paste0("<i>", gsub("_", " ", label), "</i>"))
  }
  components <- unlist(strsplit(label, "_"))
  if (grepl("subg\\.", label)) {
    new_label <- paste0("<i>",components[1],"</i> subg. <i>",components[3],"</i>")
    return(new_label)
  }
  paste0(gsub("_", " ", label))
}

format_species <- function(label) {
  paste0(gsub("_", " ", label))
}

for (n in subtree_nodes) {
  subtree <- tidytree::tree_subset(tree, n, levels_back = 0)
  if (length(subtree@phylo$tip.label) < 2) next 
  
  root_taxon_node <- as_tibble(tree) |> filter(node == n)
  root_taxon <- root_taxon_node |> pull(label)
  p_sub <- ggtree(subtree) +
    geom_tiplab(size = 3, aes(label = mapply(format_species, label)), fontface = "italic") +
    geom_richtext(
      data = td_filter(!isTip),
      aes(label = mapply(format_node_label, label, rank)),
      size = 2, na.rm = TRUE,
      fill = 'lightblue', label.color = NA
    ) +
    hexpand(0.3) + vexpand(0.5)
  plots[[length(plots) + 1]] <- list(p = p_sub, w = 12, h = fig_height(subtree), label = root_taxon)
}

for (i in seq_along(plots)) {
  p <- plots[[i]]
  chunk <- knitr::knit_expand(
    text = c(
      "```{r fig-{{label}}, fig.height={{h}}, fig.width=8, fig.cap='{{label}}', echo=FALSE}",
      "plots[[{{i}}]]$p",
      "```"
    ),
    i = i,
    h = plots[[i]]$h,
    label = plots[[i]]$label
  )
  cat(knitr::knit(text = chunk, quiet = TRUE))
  cat("\n\n")
}
```


```{=latex}
\newpage
```

# Descriptions

## Phylum Manubristenta
**Manubristenta** Lemuria, 2026; first public desc.

**Taxonomic placement**: Placed in the kingdom Abtruncusa.

**Diagnosis**: Phenetically, Manubristenta is characterized by the exposure of the skin superficial to the manubrium, the superior (upper) part of the sternum (breastbone), and covered shoulders.

## Subphylum Quaracomorpha
**Quaracomorpha** Lemuria, 2026; first public desc.

**Taxonomic placement**: Placed in the phylum Manubristenta.

**Diagnosis**: Phenetically, Quaracomorpha is characterized by a square neckline.

## Class Kampylilaimosida
**Kampylilaimosida** Lemuria, 2026; first public desc.

**Taxonomic placement**: Placed in the subphylum Quaracomorpha.

**Diagnosis**: Phenetically, Kampylilaimosida is characterized by a square neckline with curved edges.

**Etymology**: From Greek καμπύλη (*kampýli*, 'curve') + λαιμός (*laimós*, "neck"); lit. "curved neck".

## Order Sueciargenta
**Sueciargenta** Lemuria, 2026; first public desc.

**Taxonomic placement**: Placed in the class Kampylilaimosida.
<!--
Domain **Vestimentia** > Kingdom **Abtruncusa** > Phylum **Manubristenta** > Subphylum **Quaracomorpha** > Class **Kampylilaimosida** > Order **Sueciargenta** -->

**Diagnosis**: Phylogenetically, Sueciargenta is characterized by descent from a Silversaga pattern, and phenetically, by a square neckline with curved edges.

**Etymology**: From Latin *Suecia* ("Sweden") + *argenta*, feminine form of *argentum* ("silver").

### Family Argenteleonoridae
**Argenteleonoridae** Lemuria, 2026; first public desc.

#### Genus *Argenteleonora*
***Argenteleonora*** Lemuria, 2026; first public desc.

#### *Argenteleonora* subg. *Shira*
***Argenteleonora* subgenus *Shira*** Lemuria, 2026; first public desc.

##### *Argenteleonora ariae* {#sec-argenteleonora-ariae}
***Argenteleonora ariae*** Lemuria, 2026; first public desc.

##### *Argenteleonora felicitae* {#sec-argenteleonora-felicitae}
***Argenteleonora felicitae*** Lemuria, 2026; first public desc.

##### *Argenteleonora madalinae* {#sec-argenteleonora-madalinae}
***Argenteleonora madalinae*** Lemuria, 2026; first public desc.

##### *Argenteleonora madeleinae* {#sec-argenteleonora-madeleinae}
***Argenteleonora madeleinae*** Lemuria, 2026; first public desc.

##### *Argenteleonora madeleinatra* {#sec-argenteleonora-madeleinatra}
***Argenteleonora madeleinatra*** Lemuria, 2026; first public desc.

##### *Argenteleonora mantorae* {#sec-argenteleonora-mantorae}
***Argenteleonora mantorae*** Lemuria, 2026; first public desc.

##### *Argenteleonora manuelae* {#sec-argenteleonora-manuelae}
***Argenteleonora manuelae*** Lemuria, 2026; first public desc.

##### *Argenteleonora martae* {#sec-argenteleonora-martae}
***Argenteleonora martae*** Lemuria, 2026; first public desc.

##### *Argenteleonora rubra* {#sec-argenteleonora-rubra}
***Argenteleonora rubra*** Lemuria, 2026; first public desc.

##### *Argenteleonora stephania* {#sec-argenteleonora-stephania}
***Argenteleonora stephania*** Lemuria, 2026; first public desc.

##### *Argenteleonora thea* {#sec-argenteleonora-thea}
***Argenteleonora thea*** Lemuria, 2026; first public desc.

##### *Argenteleonora veneta* {#sec-argenteleonora-veneta}
***Argenteleonora veneta*** Lemuria, 2026; first public desc.

#### *Argenteleonora* subg. *Elastica*
***Argenteleonora* subgenus *Elastica*** Lemuria, 2026; first public desc.

#### *Argenteleonora* sect. *Unilastica*
***Argenteleonora* section *Unilastica*** Lemuria, 2026; first public desc.

##### *Argenteleonora annettae* {#sec-argenteleonora-annettae}
***Argenteleonora annettae*** Lemuria, 2026; first public desc.

#### *Argenteleonora* sect. *Duolastica*

<!-- Template generated with lct01tools and manually filled in by humans! -->
##### *Argenteleonora bethanae* {#sec-argenteleonora-bethanae}
***Argenteleonora bethanae*** Lemuria, 2026

**Diagnosis**: *Argenteleonora bethanae* is characterized by its fabric, a cotton dimity lawn from Lyrical Fabrics, dyed off-white with tea.

**Remarks**: Bethany made the dress in size EU 38 (US 8, UK 10). She cut two skirt panels at the full width of the fabric (55 in; ~139.7 cm), as opposed to the four panels specified by the pattern [@bethany2025, Eleonora Dress].

**Tea fabric**. In April 2024, Bethany dyed *A. bethanae* in tea to diminish its fabric's bright white color to a slight off-white brown. [@bethany2024].

Bethany used 114 packets of English Breakfast black tea from Benner Tea Co, placed in a pot with 3.8 liters of water. Black tea most likely from leaves of *Camellia sinensis* (L.) Kuntze. Tea bags were gradually added to the boiling water, which was steeped for 15 minutes with occasional stirring. A strainer was then used to remove the tea bags. The tea was strained through scrap fabric into a large bowl. Bethany recommends a loosely woven fabric such as cheesecloth for straining, and the use of a stainless steel bowl to prevent tea stains. [@bethany2024].

*A. bethanae* was submerged in a sink with 15 liters of hot water, mixed with five cups (est. 1182.941 ml) of white vinegar, a roughly 15:1 hot water&ndash;vinegar ratio [@bethany2024], which diverged from the 1:4 ratio recommended by @koshimizu2018.

The tea was then poured into a plastic tub, then diluted with three pots (est. 12 liters; fill height unknown) of water. *A. bethanae* was then submerged in the tea. It was pushed deeper into the water to remove air bubbles and swirled continuously for 15 minutes to ensure even dispersion of the tea dye across the dress. The dress was then held over a sink and rinsed with cool water until the water ran clear. [@bethany2024].

In @koshimizu2018, which Bethany cites, the fabric was soaked in a 1:2 ratio of cold water&ndash;vinegar and then rinsed. However, Bethany skipped this step due to insufficient vinegar. The dress was then squeezed and placed on a plastic hanger to dry. The dress was then placed in a gentle wash cycle with a mild detergent and dried in a dryer [@bethany2024].

Bethany wrote her own blog post detailing the process [@bethany2024], and cited a blog post from the *Woodlark Blog* [@koshimizu2018].

The change in color of the fabric is perhaps the first example of anagenesis in the LCT-01.

**Varieties**:

* *A. bethanae* var. *brunathea* &mdash; type variety. From Medieval Latin *bruna* ("brown") + New Latin *thea* ("tea").
* &dagger;*A. bethanae* var. *athea* &mdash; pre-dyed variant. From Greek *a-* ("no") + New Latin *thea* ("tea"). Rendered extinct by anagenesis into var. *brunathea* as documented in @bethany2024.

<!-- (Forms are used for configurations in which the dress is worn) -->

**Etymology**: From *Bethany* + *-ae*, Latin feminine genitive suffix.

**Specimens examined**

**Holotype**: ***Bethany 108.5716*** &mdash; Photograph.
3024&times;4032.
Ventral view. Daytime lighting. Subject standing indoors, window to her right. Partially in shadow. Subject's arms fully adducted, with her right foot stretched out. Hair positioned ventrally.
*Argenteleonora bethanae* var. *athea* wb. Bethany.L., YEAR.
&copy; Bethany Lynne or unknown photographer, all rights reserved.
**Page**: @eleonora_gallery; 
**SHA2-256**: `a1aef642f44c5bfbb6f8c00a6911e7a32e5df31252e71fd7a4330e4edf90ddf2`{.hash};
**Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Bethany_Routamaa.jpg?v=1713471765>;
**IA**: <https://web.archive.org/web/20260408095302/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Bethany_Routamaa.jpg?v=1713471765>

*Bethany 108.1798* &mdash; Photograph.
3024&times;4032.
Dorsal view. Daytime lighting. Subject standing indoors, same room as *Bethany 108.5716*, shadow slightly larger. Hair tied and positioned dorsally, running laterally across right scapula. Subject's right arm adducted.
EXIF metadata stripped.
*Argenteleonora bethanae* var. *athea* wb. Bethany.L., YEAR. <!-- TODO: year -->
&copy; Bethany Lynne or unknown photographer, all rights reserved.
**Page**: @eleonora_gallery;
**SHA2-256**: `06ea6f6c2a8b08aebdc8475aa43da82767211842ac11b0162b3bba8b9ccc204f`{.hash};
**Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Bethany_Routamaa2.jpg?v=1713471798>;
**IA**: <https://web.archive.org/web/20260408095308/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Bethany_Routamaa2.jpg?v=1713471798>

*Bethany 108.1763* &mdash; Photograph.
2316&times;3088.
Ventral view, white wall. Apparent light source from subject's right. Truncated view; subject's head not shown.
EXIF metadata stripped.
*Argenteleonora bethanae* var. *athea* wb. Bethany.L., YEAR. <!-- TODO: year -->
&copy; Bethany Lynne or unknown photographer, all rights reserved.
**Page**: @eleonora_gallery;
**SHA2-256**: `9d5ed53970c97a161cdccd7835b1ed80b62a6aac2ae4723c22f9d84e92caaf77`{.hash};
**Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Bethany_Routamaa4.jpg?v=1713471720>;
**IA**: <https://web.archive.org/web/20260408095300/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Bethany_Routamaa4.jpg?v=1713471720>

*Bethany 108.1902* &mdash; Photograph. 
1200&times;1600.
Ventral view, outdoor lighting. Subject's arms fully adducted. Truncated view; area of head superior to lips not shown.
EXIF metadata stripped. Last-Modified header 2024-04-19. "Encoded with Blend=1 downsampling" Filename `floral-dress-after-dyeing-with-tea.jpg`.
EXIF metadata stripped.
*Argenteleonora bethanae* var. *brunathea* wb. Bethany.L., 2024.
**Page**: @bethany2024
**SHA2-256**: `4ae10225373623f7c9235d127f345a7395b5a5fd16c0cd5f56e967e49a34fa43`{.hash}
**Original**: <https://www.bethanylynnemakes.com/wp-content/uploads/2024/04/floral-dress-after-dyeing-with-tea.jpg>;
**IA**: <https://web.archive.org/web/20260409051700/https://www.bethanylynnemakes.com/wp-content/uploads/2024/04/floral-dress-after-dyeing-with-tea.jpg>

##### *Argenteleonora patriciae* {#sec-argenteleonora-patriciae}
***Argenteleonora patriciae*** Lemuria, 2026; first public desc.

**Diagnosis**: *Argenteleonora patriciae* is characterized by its black rayon crepe fabric, an Indian block print in black, cream, gold taupe, and Irish green. Bodice lengthened by 2 in (5.08 cm) and neckline raised by 1 in (2.54 cm).

**Etymology**: From *Patricia* + *-ae*, Latin feminine genitive suffix.

**Specimens examined**

**Holotype**: ***Rainey 17.15090*** &mdash; Photograph.
3024&times;4032
*Argenteleonora patriciae* wb. Patricia.R., 2024.
&copy; Patricia Rainey or unknown photographer, all rights reserved.
**Page**: @rainey2025;
**SHA2-256**: `f9429b926183edb3f89a87181d688a9dd72912cb301f55a22303ccd364e49ce5`{.hash};
**Original**: <https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi1dHKRKxf8cgUtT2Yvqy3nJ_drE48a6FTmAmS9YHGYq5jERJ1o4EOMarz9q8ibmHuyVICN_ZxXDbYrZEC4lmGpK0KbsJi6XzP-F_sIH2K-pPzam5PmLKh88OgyW59mFtLN5ugHjKYnz8srx7Wsq8MtY5PII9PfiYc_yFqfBWWOMvEbmp1KO3y9r5R478U3/s0/Picture%201.jpg=s0?imgmax=0>;
**IA**: <https://web.archive.org/web/20260409070218/https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi1dHKRKxf8cgUtT2Yvqy3nJ_drE48a6FTmAmS9YHGYq5jERJ1o4EOMarz9q8ibmHuyVICN_ZxXDbYrZEC4lmGpK0KbsJi6XzP-F_sIH2K-pPzam5PmLKh88OgyW59mFtLN5ugHjKYnz8srx7Wsq8MtY5PII9PfiYc_yFqfBWWOMvEbmp1KO3y9r5R478U3/s0/Picture%201.jpg=s0?imgmax=0>;

*Rainey 17.21134* &mdash; Photograph.
3024&times;4032
*Argenteleonora patriciae* wb. Patricia.R., 2024.
&copy; Patricia Rainey or unknown photographer, all rights reserved.
**Page**: @rainey2025;
**SHA2-256**: `9c0eba94ee320e8d77cf71881bdd08958d0eb60263d861a11adb2edb7fac7f9e`{.hash};
**Original**: <https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiJgyEfoyufy0LV2ynuIzvePtJ8E_O8686movABhyphenhyphenY3E7gsy59uYiPzEIHFJeKIU9Tp0RXZaPfXrv12CU-1OiNqyn5fWFmB5odbtdMY3Bdb9j1u8uWAfBS_vjdd0yXHLipqarYTtYsw9rxsbLDNOaC1ZcSrD9Jam7QyPi5AU1gr0QlhPrB4mtQ-F1-mWLBd/s0/Picture%202.jpg=s0?imgmax=0>;
**IA**: <https://web.archive.org/web/20260409070227/https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiJgyEfoyufy0LV2ynuIzvePtJ8E_O8686movABhyphenhyphenY3E7gsy59uYiPzEIHFJeKIU9Tp0RXZaPfXrv12CU-1OiNqyn5fWFmB5odbtdMY3Bdb9j1u8uWAfBS_vjdd0yXHLipqarYTtYsw9rxsbLDNOaC1ZcSrD9Jam7QyPi5AU1gr0QlhPrB4mtQ-F1-mWLBd/s0/Picture%202.jpg=s0?imgmax=0>;
  
*Rainey 17.21167* &mdash; Photograph.
3024&times;4032
*Argenteleonora patriciae* wb. Patricia.R., 2024.
&copy; Patricia Rainey or unknown photographer, all rights reserved.
**Page**: @rainey2025;
**SHA2-256**: `ff5dda3d4bee5c846664cdf790278d490b2b4b63e84e3d0a1da1c53ae92f939a`{.hash};
**Original**: <https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgI7xEsHxAH_esazviAjnH5Q3x6yc4aGuHpMDO5GaDYQ4cuoI4RYPhIl6F5HVAhQky82YuOeOMcukTjjN1wvdmB_QhbG16I5vEY_SYjFI7uW3B0AHojxjwoQnsEOMXtxEz1OjW76UrDwf8r6rQV5ZCFN0A4QSSRPW5yG2umxcdDIx9WRRDvIrSOvsrMHboL/s0/Picture%204.jpg=s0?imgmax=0>;
**IA**: <https://web.archive.org/web/20260409070230/https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgI7xEsHxAH_esazviAjnH5Q3x6yc4aGuHpMDO5GaDYQ4cuoI4RYPhIl6F5HVAhQky82YuOeOMcukTjjN1wvdmB_QhbG16I5vEY_SYjFI7uW3B0AHojxjwoQnsEOMXtxEz1OjW76UrDwf8r6rQV5ZCFN0A4QSSRPW5yG2umxcdDIx9WRRDvIrSOvsrMHboL/s0/Picture%204.jpg=s0?imgmax=0>;
  
*Rainey 17.21190* &mdash; Photograph.
3024&times;4032
*Argenteleonora patriciae* wb. Patricia.R., 2024.
&copy; Patricia Rainey or unknown photographer, all rights reserved.
**Page**: @rainey2025;
**SHA2-256**: `6412a063856f56bf77d12e9f312a7da7a3185815534a8a800f95f80b44ff5595`{.hash};
**Original**: <https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiHuYQ9l6wRwPWS9hn5-4ucLrU6KeqZhyphenhyphenC31nl03HMF0uvN_6PzjWsjqPuPHrJX00tpmrePsOSvlPAUTrNkVQ47m1gt-MofkepTqFGk_1WkYLNRg2p_C_UfS0DBtx3iNEtIG8jkwJwzjG-shlWpIN6t_fUQvwBi0TANfI3J1R3ynphEQc9n6EdbRdb9dhNw/s0/Picture%205.jpg=s0?imgmax=0>;
**IA**: <https://web.archive.org/web/20260409070158/https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiHuYQ9l6wRwPWS9hn5-4ucLrU6KeqZhyphenhyphenC31nl03HMF0uvN_6PzjWsjqPuPHrJX00tpmrePsOSvlPAUTrNkVQ47m1gt-MofkepTqFGk_1WkYLNRg2p_C_UfS0DBtx3iNEtIG8jkwJwzjG-shlWpIN6t_fUQvwBi0TANfI3J1R3ynphEQc9n6EdbRdb9dhNw/s0/Picture%205.jpg=s0?imgmax=0>;
  
*Rainey 17.25400* &mdash; Photograph.
3024&times;4032
*Argenteleonora patriciae* wb. Patricia.R., 2024.
&copy; Patricia Rainey or unknown photographer, all rights reserved.
**Page**: @rainey2025;
**SHA2-256**: `2e8f2d6c921bc8eb5bcfb3f670c4351100460134350ae5566b56214f6fb431d8`{.hash};
**Original**: <https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgXOx7LbOzdD139kTIyH6x0TyAd3dwlaaxeGcqit5NGaTbaEe6q_m0Ew473VVvMGVE9mlJdfhCCqyY2rY4r-juqkRasD3ZBCH6PYjObI5eXAI8egaR-sf_jgtfq1615VYTApmJRwRkIUrmaZ-LPIC5BhIV89M97jGGj1ZbQPXr33dp99by_KIunzBEQyq-t/s0/Picture%206.jpg=s0?imgmax=0>;
**IA**: <https://web.archive.org/web/20260409070147/https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgXOx7LbOzdD139kTIyH6x0TyAd3dwlaaxeGcqit5NGaTbaEe6q_m0Ew473VVvMGVE9mlJdfhCCqyY2rY4r-juqkRasD3ZBCH6PYjObI5eXAI8egaR-sf_jgtfq1615VYTApmJRwRkIUrmaZ-LPIC5BhIV89M97jGGj1ZbQPXr33dp99by_KIunzBEQyq-t/s0/Picture%206.jpg=s0?imgmax=0>;
  
*Rainey 17.25463* &mdash; Photograph.
3024&times;4032.
*Argenteleonora patriciae* wb. Patricia.R., 2024.
&copy; Patricia Rainey or unknown photographer, all rights reserved.
**Page**: @rainey2025;
**SHA2-256**: `e1d5f12b877d7337a0e92fba7bef1970900556968f6e330ebdec98766bc733ec`{.hash};
**Original**: <https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgtOVXtLRLIKfMqa5UOnwZ8SOPzKqJ7IXUZ6JtIXsMksHBhZxqUxeQWz0C7GReVb0T1DhFv8Zl9c1PmpvaHkqc55gl3b3IO367mME_cIIGv-nGTWq8LFHwtsH3SBynIBlMy-oii-Pz5C-L50cUbwHqeYlwAvxi6gxkQEMos0ROdTM-VG7NVmfM4_N1rxKwe/s0/Picture%207.jpg=s0?imgmax=0>;
**IA**: <https://web.archive.org/web/20260409070122/https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgtOVXtLRLIKfMqa5UOnwZ8SOPzKqJ7IXUZ6JtIXsMksHBhZxqUxeQWz0C7GReVb0T1DhFv8Zl9c1PmpvaHkqc55gl3b3IO367mME_cIIGv-nGTWq8LFHwtsH3SBynIBlMy-oii-Pz5C-L50cUbwHqeYlwAvxi6gxkQEMos0ROdTM-VG7NVmfM4_N1rxKwe/s0/Picture%207.jpg=s0?imgmax=0>;
  
*Rainey 17.27101* &mdash; Photograph.
3024&times;4032.
*Argenteleonora patriciae* wb. Patricia.R., 2024.
&copy; Patricia Rainey or unknown photographer, all rights reserved.
**Page**: @rainey2025;
**SHA2-256**: `f89399a53bc32584ab42fdf85b47753c5cdbf121b9b87822be1bdf055a1a327e`{.hash};
**Original**: <https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEibdvEZ6RwnNIEfxHqtzxaY6yRXXiQ8fv61O4aCXFv515Cl4eZv-PmUEHcj0eIWmBy8Qm45wUG9PuBQz4iFJEFraBhdTFa3eLULi8GKV-Nd7-XPTqrbhgHoncEkrLiSpuks7IvDxOAxhVUCFpudbopuU5qnO5i3QPIvgHuVmL_WjZtfHe0e8Z3GJlX1QXQm/s0/Picture%2013.jpg=s0?imgmax=0>;
**IA**: <https://web.archive.org/web/20260409070048/https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEibdvEZ6RwnNIEfxHqtzxaY6yRXXiQ8fv61O4aCXFv515Cl4eZv-PmUEHcj0eIWmBy8Qm45wUG9PuBQz4iFJEFraBhdTFa3eLULi8GKV-Nd7-XPTqrbhgHoncEkrLiSpuks7IvDxOAxhVUCFpudbopuU5qnO5i3QPIvgHuVmL_WjZtfHe0e8Z3GJlX1QXQm/s0/Picture%2013.jpg=s0?imgmax=0>;
  
*Rainey 17.27161* &mdash; Photograph.
3024&times;4032.
*Argenteleonora patriciae* wb. Patricia.R., 2024.
&copy; Patricia Rainey or unknown photographer, all rights reserved.
**Page**: @rainey2025;
**SHA2-256**: `da641328888bb56232c686852c6657e5c63bbc39306cb389a63e0ae5c6f02cf3`{.hash};
**Original**: <https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgOADu0sRh_zt8JzZ3U9FiM0VZWDNpDOt9rqGlw-PUV8EuNmLjgnmets4eZfllKD-H1naUZogJ1kOpfafs8mgUSs0sVZSRB2qilfG0roru6qpvxmtz6Q25QB9pzYxi_6mKkNilIus3YYk5mABTT_0ANuHG3EtV0x56cScYK0cTnrKAHpqbDqQVQaUPRQOLY/s0/Picture%2015.jpg=s0?imgmax=0>;
**IA**: <https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgOADu0sRh_zt8JzZ3U9FiM0VZWDNpDOt9rqGlw-PUV8EuNmLjgnmets4eZfllKD-H1naUZogJ1kOpfafs8mgUSs0sVZSRB2qilfG0roru6qpvxmtz6Q25QB9pzYxi_6mKkNilIus3YYk5mABTT_0ANuHG3EtV0x56cScYK0cTnrKAHpqbDqQVQaUPRQOLY/s0/Picture%2015.jpg%3Ds0?imgmax=0>;

*Rainey 17.30145* &mdash; Photograph.
3024&times;4032.
*Argenteleonora patriciae* wb. Patricia.R., 2024.
&copy; Patricia Rainey or unknown photographer, all rights reserved.
**Page**: @rainey2025;
**SHA2-256**: `d2eb52cfcecd175041e4bd9ee8d7a7af53ea2ba7fcf53debf9731fb1d179a5b8`{.hash};
**Original**: <https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgD28QTOKpyC2aCMkxtSbm2Mg1GqVFZNtCZFHRQ3N2S6xZVjDJwjIhd2XP_ifCFRbnSpIoJEoeSvHrOLcIrdruInUDQiCpMzTQ5skfupdCQAumI4DiuLnWGm0khMoV__mCSioPsv0ugleV9bk4l_BGfvDTH-nMVY2w5_SST0F3cyLYfJZeugMTrzza8mkye/s0/Picture%2016.jpg=s0?imgmax=0>;
**IA**: <https://web.archive.org/web/20260409065957/https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgD28QTOKpyC2aCMkxtSbm2Mg1GqVFZNtCZFHRQ3N2S6xZVjDJwjIhd2XP_ifCFRbnSpIoJEoeSvHrOLcIrdruInUDQiCpMzTQ5skfupdCQAumI4DiuLnWGm0khMoV__mCSioPsv0ugleV9bk4l_BGfvDTH-nMVY2w5_SST0F3cyLYfJZeugMTrzza8mkye/s0/Picture%2016.jpg=s0?imgmax=0>;

##### *Argenteleonora katiae* {#sec-argenteleonora-katiae}
***Argenteleonora katiae*** Lemuria, 2026; first public desc.

## Order Helargenta
**Helargenta** Lemuria, 2026; first public desc.

### Family Heleonoridae
**Heleonoridae** Lemuria, 2026; first public desc.

#### Genus *Heleonora*
***Heleonora*** Lemuria, 2026; first public desc.

#### *Heleonora* subg. *Shira*
***Heleonora* subgenus *Shira*** Lemuria, 2026; first public desc.

**Diagnosis**: Phenetically, *Heleonora subg. Shira* is characterized by 

**Etymology**:

<!-- replace taxon with the name of the rank! -->
**Type taxon**:
<!-- Template generated with lct01tools and manually filled in by humans! -->

<!-- Template generated with lct01tools and manually filled in by humans! -->
##### *Heleonora lizzia* {#sec-heleonora-lizzia}
***Heleonora lizzia*** Lemuria, 2026; first public desc.

**Holotype**: ***McNally 20.23014*** &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora lizzia* wb. Elizabeth.M., YEAR.
&copy; Elizabeth McNally or unknown photographer, all rights reserved.

* **Page**: 
* **SHA2-256**: `6f27893b736fbebf44fbfc24fec10afd2487c4cda1d91daec6de441a9bfbf77b`{.hash}
* **Raw image URLs**
  * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Elizabeth_McNally2.jpg?v=1720291681>
  * **IA**: <https://web.archive.org/web/20260408095919/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Elizabeth_McNally2.jpg?v=1720291681>

**Diagnosis**: *Heleonora lizzia* is characterized by

**Description**:

**Remarks**:

**Etymology**: From

**Specimens examined**:

* Holotype.
* *McNally 20.23710* &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora lizzia* wb. Elizabeth.M., YEAR.
&copy; Elizabeth McNally or unknown photographer, all rights reserved.
  * **Page**: 
  * **SHA2-256**: `f46504965fb55a6e9a4ac4c7cab6f2e9835967042cf474b5e9162b4f9ec90bee`{.hash}
  * **Raw image URLs**
    * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Elizabeth_McNally3.jpg?v=1720291681>
    * **IA**: <https://web.archive.org/web/20260408095920/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Elizabeth_McNally3.jpg?v=1720291681>
  
<!-- Template generated with lct01tools and manually filled in by humans! -->
##### *Heleonora fraxina* {#sec-heleonora-fraxina}
***Heleonora fraxina*** Lemuria, 2026; first public desc.

**Holotype**: ***Ashley 931.1620*** &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora fraxina* wb. Ashley.G., YEAR.
&copy; Ashley General or unknown photographer, all rights reserved.

* **Page**: 
* **SHA2-256**: `3c9c348550c7b6df497d8d64f23d4b320d75f521eae6b518980f0995cff2cee3`{.hash}
* **Raw image URLs**
  * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Ashley_General.jpg?v=1720291730>
  * **IA**: <https://web.archive.org/web/20260408095919/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Ashley_General2.jpg?v=1720291729>

**Diagnosis**: *Heleonora fraxina* is characterized by

**Description**:

**Remarks**:

**Etymology**: From

**Specimens examined**:

* Holotype.
* *Ashley 931.1744* &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora fraxina* wb. Ashley.G., YEAR.
&copy; Ashley General or unknown photographer, all rights reserved.
  * **Page**: 
  * **SHA2-256**: `fe06a0b9b231c960af85b806a2620b21d0e040b42ee4f538f75deeec67210773`{.hash}
  * **Raw image URLs**
    * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Ashley_General2.jpg?v=1720291729>
    * **IA**: <https://web.archive.org/web/20260408095925/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Ashley_General.jpg?v=1720291730>
  
* *Ashley 931.1763* &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora fraxina* wb. Ashley.G., YEAR.
&copy; Ashley General or unknown photographer, all rights reserved.
  * **Page**: 
  * **SHA2-256**: `9e8cb857a04dfb6b41e9bc7ea8b395eeee8b1bd6b40399cfb958a71b2acf9d0c`{.hash}
  * **Raw image URLs**
    * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Ashley_General6.jpg?v=1720291726>
    * **IA**: <https://web.archive.org/web/20260408100029/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Ashley_General6.jpg?v=1720291726>
  
<!-- Template generated with lct01tools and manually filled in by humans! -->
##### *Heleonora beatricae* {#sec-heleonora-beatricae}
***Heleonora beatricae*** Lemuria, 2026; first public desc.

**Holotype**: ***Beatrice 210.1631*** &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora beatricae* wb. Beatrice.F., YEAR.
&copy; Beatrice Fletcher or unknown photographer, all rights reserved.

* **Page**: 
* **SHA2-256**: `52713bac98440233620dc64800dc05459ddb6af333952c459f0a83ba84310402`{.hash}
* **Raw image URLs**
  * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Beatrice_Fletcher3.heic?v=1720291673>
  * **IA**: <https://web.archive.org/web/20260408100107/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Beatrice_Fletcher3.heic?v=1720291673>

**Diagnosis**: *Heleonora beatricae* is characterized by

**Description**:

**Remarks**:

**Etymology**: From

**Specimens examined**:

* Holotype.
* *Beatrice 210.1651* &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora beatricae* wb. Beatrice.F., YEAR.
&copy; Beatrice Fletcher or unknown photographer, all rights reserved.
  * **Page**: 
  * **SHA2-256**: `883570d98927a3cbf540d6c29bbccf307062ab73da1041794ad9d2321f889884`{.hash}
  * **Raw image URLs**
    * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Beatrice_Fletcher4.heic?v=1720291673>
    * **IA**: <https://web.archive.org/web/20260408100108/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Beatrice_Fletcher4.heic?v=1720291673>
  
<!-- Template generated with lct01tools and manually filled in by humans! -->
##### *Heleonora meganae* {#sec-heleonora-meganae}
***Heleonora meganae*** Lemuria, 2026; first public desc.

**Holotype**: ***Megan 171.4071*** &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora meganae* wb. Megan.B., YEAR.
&copy; Megan Bynum or unknown photographer, all rights reserved.

* **Page**: 
* **SHA2-256**: `8d57cce69d2db026e6a7a21a939d497b11896aaaed99ce8935aba1e5cc0d3b6b`{.hash}
* **Raw image URLs**
  * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Megan_Bynum.jpg?v=1720291697>
  * **IA**: <https://web.archive.org/web/20260408100428/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Megan_Bynum.jpg?v=1720291697>

**Diagnosis**: *Heleonora meganae* is characterized by

**Description**:

**Remarks**:

**Etymology**: From

**Specimens examined**:

* Holotype.
* *Megan 171.4098* &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora meganae* wb. Megan.B., YEAR.
&copy; Megan Bynum or unknown photographer, all rights reserved.
  * **Page**: 
  * **SHA2-256**: `c2ead0e6bb186daf48fc5e90df12a701c0f32069b7f6b74211094652796f38c7`{.hash}
  * **Raw image URLs**
    * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Megan_Bynum2.jpg?v=1720291697>
    * **IA**: <https://web.archive.org/web/20260408100829/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Megan_Bynum2.jpg?v=1720291697>
  
<!-- Template generated with lct01tools and manually filled in by humans! -->
##### *Heleonora nellia* {#sec-heleonora-nellia}
***Heleonora nellia*** Lemuria, 2026; first public desc.

**Holotype**: ***Nelly 233.9071*** &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora nellia* wb. Nelly.C., YEAR.
&copy; Nelly Colne or unknown photographer, all rights reserved.

* **Page**: 
* **SHA2-256**: `d2b3950c36319184ea909bf88d3eb59e7b2947c2dd8b41fc23a4d37851671f12`{.hash}
* **Raw image URLs**
  * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Nelly_Colne11.jpg?v=1720292012>
  * **IA**: <https://web.archive.org/web/20260408100615/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Nelly_Colne11.jpg?v=1720292012>

**Diagnosis**: *Heleonora nellia* is characterized by

**Description**:

**Remarks**:

**Etymology**: From

**Specimens examined**:

* Holotype.
* *Nelly 233.9085* &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora nellia* wb. Nelly.C., YEAR.
&copy; Nelly Colne or unknown photographer, all rights reserved.
  * **Page**: 
  * **SHA2-256**: `dd9d50d4944641371e7220e049d796a90901c293bfdd8dc2f23763e9db9d5c37`{.hash}
  * **Raw image URLs**
    * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Nelly_Colne5_a27a2593-3a57-4991-8819-696e1fa73532.jpg?v=1720292984>
    * **IA**: <https://web.archive.org/web/20260408100725/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Nelly_Colne5_a27a2593-3a57-4991-8819-696e1fa73532.jpg?v=1720292984>
  
<!-- Template generated with lct01tools and manually filled in by humans! -->
##### *Heleonora shreyae* {#sec-heleonora-shreyae}
***Heleonora shreyae*** Lemuria, 2026; first public desc.

**Holotype**: ***Shreya 59.5165*** &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora shreyae* wb. Shreya, YEAR.
&copy; Shreya or unknown photographer, all rights reserved.

* **Page**: 
* **SHA2-256**: `9fcf9592f703998480b966a3217d4eb2bfe8c49f8da04ac7d7488f893a632b0d`{.hash}
* **Raw image URLs**
  * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Shreya_Eleonora_2.jpg?v=1720291714>
  * **IA**: <https://web.archive.org/web/20260408100217/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Shreya_Eleonora_2.jpg?v=1720291714>

**Diagnosis**: *Heleonora shreyae* is characterized by

**Description**:

**Remarks**:

**Etymology**: From

**Specimens examined**:

* Holotype.
* *Shreya 59.5166* &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora shreyae* wb. Shreya, YEAR.
&copy; Shreya or unknown photographer, all rights reserved.
  * **Page**: 
  * **SHA2-256**: `d1eea0276e361b393c523ae9fade4d905983e9c9657ef9e3ca3270acd4164da2`{.hash}
  * **Raw image URLs**
    * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Shreya_Eleonora_3.jpg?v=1720291714>
    * **IA**: <https://web.archive.org/web/20260408100230/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Shreya_Eleonora_3.jpg?v=1720291714>
  
<!-- Template generated with lct01tools and manually filled in by humans! -->
##### *Heleonora rimforsia* {#sec-heleonora-rimforsia}
***Heleonora rimforsia*** Lemuria, 2026; first public desc.

**Holotype**: ***Rimfors 15.1660*** &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora rimforsia* wb. Rimfors, YEAR.
&copy; Tuss Rimfors or unknown photographer, all rights reserved.

* **Page**: 
* **SHA2-256**: `383343b7930238147ad2ca06e3e59dee8993a8b7bdec559fb567671ba3167ebf`{.hash}
* **Raw image URLs**
  * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Tuss_Rimfors.heic?v=1720291720>
  * **IA**: <https://web.archive.org/web/20260408100536/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Tuss_Rimfors.heic?v=1720291720>

**Diagnosis**: *Heleonora rimforsia* is characterized by

**Description**:

**Remarks**:

**Etymology**: From

**Specimens examined**:

* Holotype.
* *Rimfors 15.1710* &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora rimforsia* wb. Rimfors, YEAR.
&copy; Tuss Rimfors or unknown photographer, all rights reserved.
  * **Page**: 
  * **SHA2-256**: `1bd85dd6679d51c2409bb562bb83f96212eaef3d496e66044a0ba7da89f8f1dd`{.hash}
  * **Raw image URLs**
    * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Tuss_Rimfors7.heic?v=1720291721>
    * **IA**: <https://web.archive.org/web/20260408100511/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Tuss_Rimfors7.heic?v=1720291721>
  
<!-- Template generated with lct01tools and manually filled in by humans! -->
##### *Heleonora anjae* {#sec-heleonora-anjae}
***Heleonora anjae*** Lemuria, 2026; first public desc.

**Holotype**: ***Anja 930.1871*** &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora anjae* wb. Anja.S., YEAR.
&copy; Anja Scheithauer or unknown photographer, all rights reserved.

* **Page**: 
* **SHA2-256**: `cfbf249735dc7e95b6bd4f5d1f5accc753b7852bf74e1504450285878030da71`{.hash}
* **Raw image URLs**
  * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Anja_Scheithauer2.jpg?v=1720291725>
  * **IA**: <https://web.archive.org/web/20260318171058/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Anja_Scheithauer2.jpg?v=1720291725>

**Diagnosis**: *Heleonora anjae* is characterized by

**Description**:

**Remarks**:

**Etymology**: From

**Specimens examined**:

* Holotype.
* *Anja 930.1724* &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora anjae* wb. Anja.S., YEAR.
&copy; Anja Scheithauer or unknown photographer, all rights reserved.
  * **Page**: 
  * **SHA2-256**: `52c1bce172348d12f1559de86ed9662dc3e003135e7ef588ce07fa370dabdb33`{.hash}
  * **Raw image URLs**
    * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Anja_Scheithauer8.jpg?v=1720291724>
    * **IA**: <https://web.archive.org/web/20260318171236/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Anja_Scheithauer8.jpg?v=1720291724>
  
<!-- Template generated with lct01tools and manually filled in by humans! -->
##### *Heleonora gabriellae* {#sec-heleonora-gabriellae}
***Heleonora gabriellae*** Lemuria, 2026; first public desc.

**Holotype**: ***Gabrielle 394.2071*** &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora gabriellae* wb. Gabrielle.Sc., YEAR.
&copy; Gabrielle Scollay or unknown photographer, all rights reserved.

* **Page**: 
* **SHA2-256**: `e208a4ee05f95f2fe58059b3e655d2195fcf9208d8a9309d99168da0076b6bf4`{.hash}
* **Raw image URLs**
  * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Gabrielle_Scollay_jpg.jpg?v=1720381421>
  * **IA**: <https://web.archive.org/web/20260408100730/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Gabrielle_Scollay_jpg.jpg?v=1720381421>

**Diagnosis**: *Heleonora gabriellae* is characterized by

**Description**:

**Remarks**:

**Etymology**: From

**Specimens examined**:

* Holotype.
* *Gabrielle 394.2049* &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora gabriellae* wb. Gabrielle.Sc., YEAR.
&copy; Gabrielle Scollay or unknown photographer, all rights reserved.
  * **Page**: 
  * **SHA2-256**: `25a03be39971e41e8e91912d46c3801fffb795520926c2484fdba235129e346b`{.hash}
  * **Raw image URLs**
    * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Gabrielle_Scollay2.jpg?v=1720381421>
    * **IA**: <https://web.archive.org/web/20260408100732/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Gabrielle_Scollay2.jpg?v=1720381421>
  
<!-- Template generated with lct01tools and manually filled in by humans! -->
##### *Heleonora ioanae* {#sec-heleonora-ioanae}
***Heleonora ioanae*** Lemuria, 2026; first public desc.

**Holotype**: ***Ioana 119.1048*** &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora ioanae* wb. Ioana.M., YEAR.
&copy; Ioana Miron or unknown photographer, all rights reserved.

* **Page**: 
* **SHA2-256**: `713958f9151fc3c00e7d41d68a03edf325fdeaf2da0209ed4e6810738368e2dc`{.hash}
* **Raw image URLs**
  * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Ioana_Miron2.jpg?v=1720291682>
  * **IA**: <https://web.archive.org/web/20260408100107/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Ioana_Miron2.jpg?v=1720291682>

**Diagnosis**: *Heleonora ioanae* is characterized by

**Description**:

**Remarks**:

**Etymology**: From

**Specimens examined**:

* Holotype.
* *Ioana 119.1057* &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora ioanae* wb. Ioana.M., YEAR.
&copy; Ioana Miron or unknown photographer, all rights reserved.
  * **Page**: 
  * **SHA2-256**: `3da5e78b8563bbe3a41410e498241465e37ffe88a9e36bd46c51f7e82a4aa528`{.hash}
  * **Raw image URLs**
    * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Ioana_Miron3.jpg?v=1720291682>
    * **IA**: <https://web.archive.org/web/20260408100223/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Ioana_Miron3.jpg?v=1720291682>
  
<!-- Template generated with lct01tools and manually filled in by humans! -->
##### *Heleonora jessae* {#sec-heleonora-jessae}
***Heleonora jessae*** Lemuria, 2026; first public desc.

**Holotype**: ***Jessa 157.1490*** &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora jessae* wb. Jessa.J., YEAR.
&copy; Jessa Jones or unknown photographer, all rights reserved.

* **Page**: 
* **SHA2-256**: `833067180a4227f0ee1acb09558c2daf507b65819925bf058c8b52da085d098f`{.hash}
* **Raw image URLs**
  * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Jessa_Jones2_650693fb-5b7a-46e7-8c63-ec487bb29e02.jpg?v=1720291686>
  * **IA**: <https://web.archive.org/web/20260408100606/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Jessa_Jones2_650693fb-5b7a-46e7-8c63-ec487bb29e02.jpg?v=1720291686>

**Diagnosis**: *Heleonora jessae* is characterized by

**Description**:

**Remarks**:

**Etymology**: From

**Specimens examined**:

* Holotype.
* *Jessa 157.12676* &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora jessae* wb. Jessa.J., YEAR.
&copy; Jessa Jones or unknown photographer, all rights reserved.
  * **Page**: 
  * **SHA2-256**: `b448220751bdb1e5f639cd6cb6f2920d31fc23ab77b6e1f8b3a71980b0ff80b6`{.hash}
  * **Raw image URLs**
    * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Jessa_Jones6.jpg?v=1720291687>
    * **IA**: <https://web.archive.org/web/20260408100607/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Jessa_Jones6.jpg?v=1720291687>
  
<!-- Template generated with lct01tools and manually filled in by humans! -->
##### *Heleonora vanhoofae* {#sec-heleonora-vanhoofae}
***Heleonora vanhoofae*** Lemuria, 2026; first public desc.

**Holotype**: ***Karen 209.1067*** &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora vanhoofae* wb. Karen V.H., YEAR.
&copy; Karen Van Hoof or unknown photographer, all rights reserved.

* **Page**: 
* **SHA2-256**: `02aafdc7e4b7b3828656eb09e6f27b06c4a3dc1bf0a096b2e994e8b847595cb8`{.hash}
* **Raw image URLs**
  * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Karen_Van_Hoof3.jpg?v=1720291688>
  * **IA**: <https://web.archive.org/web/20260408100526/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Karen_Van_Hoof3.jpg?v=1720291688>

**Diagnosis**: *Heleonora vanhoofae* is characterized by

**Description**:

**Remarks**:

**Etymology**: From

**Specimens examined**:

* Holotype.
* *Karen 209.1145* &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora vanhoofae* wb. Karen V.H., YEAR.
&copy; Karen Van Hoof or unknown photographer, all rights reserved.
  * **Page**: 
  * **SHA2-256**: `dec9990bd1c603cce11ef2d3e92b642de6905fdd57dca9559952a5fb81f0f99f`{.hash}
  * **Raw image URLs**
    * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Karen_Van_Hoof6.jpg?v=1720291689>
    * **IA**: <https://web.archive.org/web/20260408100300/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Karen_Van_Hoof6.jpg?v=1720291689>
  
<!-- Template generated with lct01tools and manually filled in by humans! -->
##### *Heleonora martinae* {#sec-heleonora-martinae}
***Heleonora martinae*** Lemuria, 2026; first public desc.

**Holotype**: ***Martina 1057.326*** &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora martinae* wb. Garofalo, YEAR.
&copy; Martina Garofalo or unknown photographer, all rights reserved.

* **Page**: 
* **SHA2-256**: `a9afef4253cd511a34a90e08a9ed98beff31740fdf76aad8f1296cd847cfd3cf`{.hash}
* **Raw image URLs**
  * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Martina_Garofalo_6.jpg?v=1720291695>
  * **IA**: <https://web.archive.org/web/20260408100404/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Martina_Garofalo_6.jpg?v=1720291696>

**Diagnosis**: *Heleonora martinae* is characterized by

**Description**:

**Remarks**:

**Etymology**: From

**Specimens examined**:

* Holotype.
* *Martina 1057.118* &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora martinae* wb. Garofalo, YEAR.
&copy; Martina Garofalo or unknown photographer, all rights reserved.
  * **Page**: 
  * **SHA2-256**: `fc7e7d791bee0d634e75a87d8078d2164542039f5014c7ce1977f4f2c76f3cd3`{.hash}
  * **Raw image URLs**
    * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Martina_Garofalo_1.jpg?v=1720291695>
    * **IA**: <https://web.archive.org/web/20260408100404/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Martina_Garofalo_1.jpg?v=1720291695>
  
<!-- Template generated with lct01tools and manually filled in by humans! -->
##### *Heleonora garciae* {#sec-heleonora-garciae}
***Heleonora garciae*** Lemuria, 2026; first public desc.

**Holotype**: ***Garcia 290.1709*** &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora garciae* wb. Stephanie.G., YEAR.
&copy; Stephanie Garcia or unknown photographer, all rights reserved.

* **Page**: 
* **SHA2-256**: `27781e0ed94d748ef0239503aa1fe6af0a2724ca7d67be1eb4e5b44f76897d54`{.hash}
* **Raw image URLs**
  * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Stephanie_Garcia20.jpg?v=1720291718>
  * **IA**: <https://web.archive.org/web/20260408100028/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Stephanie_Garcia20.jpg?v=1720291718>

**Diagnosis**: *Heleonora garciae* is characterized by

**Description**:

**Remarks**:

**Etymology**: From

**Specimens examined**:

* Holotype.
* *Garcia 290.1711* &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora garciae* wb. Stephanie.G., YEAR.
&copy; Stephanie Garcia or unknown photographer, all rights reserved.
  * **Page**: 
  * **SHA2-256**: `14ef77a944aa73506b213d6d4d01056bfc8c5d1543a935f48430e09ac2d5b12e`{.hash}
  * **Raw image URLs**
    * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Stephanie_Garcia22.jpg?v=1720291719>
    * **IA**: <https://web.archive.org/web/20260408100930/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Stephanie_Garcia22.jpg?v=1720291719>

* *Garcia 290.1736* &mdash; Photograph.
METADATAFROMHOLOTYPER
*Heleonora garciae* wb. Stephanie.G., YEAR.
&copy; Stephanie Garcia or unknown photographer, all rights reserved.
  * **Page**: 
  * **SHA2-256**: `2bb4734ba0390956aaae8eb5e29bf937e6292dfe3d5267018758284fd9896a23`{.hash}
  * **Raw image URLs**
    * **Original**: <https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Stephanie_Garcia6.jpg?v=1720291718>
    * **IA**: <https://web.archive.org/web/20260408095909/https://cdn.shopify.com/s/files/1/0562/9375/2969/files/Stephanie_Garcia6.jpg?v=1720291718>
  

#### *Heleonora* subg. *Elastica*
***Heleonora* subgenus *Elastica*** Lemuria, 2026; first public desc.

#### *Heleonora* sect. *Unilastica*
***Heleonora* section *Unilastica*** Lemuria, 2026; first public desc.

#### *Heleonora* sect. *Duolastica*
***Heleonora* section *Duolastica*** Lemuria, 2026; first public desc.

### Family Helargemmidae
**Helargemmidae** Lemuria, 2026; first public desc.

### Family Helarchloidae
**Helarchloidae** Lemuria, 2026; first public desc.

## *Incertae sedis*

### Family Argelisabethidae
**Argelisabethidae** Lemuria, 2026; familia nova

**Remarks**: Jessica cites the late 1930s and early 1940s as the inspiration for the Elisabeth.

#### Genus *Trunabethia*
***Trunabethia*** Lemuria, 2026; gen. nov.

**Remarks**: The URL for the Elisabeth blouse product page uses the slug `elvira-blouse`.

**Etymology**: Portmanteau of Latin *truncusa* ("truncated") + *Elisabeth* + *-ia*.

##### *Trunabethia ivoria*
***Trunabethia ivoria*** Lemuria, 2026; sp. nov.

##### *Trunabethia burgundia*
***Trunabethia burgundia*** Lemuria, 2026; sp. nov.

#### Genus *Argelisabethia*
***Argelisabethia*** Lemuria, 2026; gen. nov.

**Remarks**: *Argelisabethia* is one of the RTW-exclusive Silversaga taxa. It does not correspond to any known pattern available on Silversaga's website. The dress was part of Silversaga's Fall 2021 collection, and is no longer available.

Preordering for the dress ended on September 9, 2021 [@silversaga_elisabeth2021].

*Argelisabethia* is monotypic, containing only *Argelisabethia burgundia*.

**Description**: Ventral medial button row of six buttons on bodice. Buttons circular, two thread holes, thread line mostly at 0&ndash;45-degree angles. Buttons on left side of fabric.
Bilateral zippers on lateral surfaces; not visible in imagery.
Single round collar with ruffle fabric trim and bilateral curved edges, with its inferiormost points roughly parallel to the second button. First button shadowed by collar.
Straight skirt gathered by belt with medial ribbon-like tie, adjustable. Skirt terminates inferior to knee. Skirt roughly shorter than 80 cm (31 in), figure given by Silversaga for garment's waist-to-hem length.
Sleeve gathered across entire length, terminating superior to elbow in an elastic channel at distal end with gathered fabric trim. Width of elastic channel roughly equivalent to diameter of one button.
**Fabric**. Lightweight rayon crêpe from Italy. Likely exclusive to Silversaga.

**Etymology**: Portmanteau of *Argenta-*, Silversaga brand suffix + *Elisabeth* + *-ia*.

**Type species**: *Argelisabethia burgundia*

##### *Argelisabethia burgundia*
***Argelisabethia burgundia*** Lemuria, 2026; sp. nov.

**Diagnosis**: *Argelisabethia burgundia* is distinguished by its burgundy fabric.

**Remarks**: Model unnamed, provisionally designated `W/2026 G17`. Body size EU 34 (X-small). 1.65&nbsp;m (5&nbsp;ft 5&nbsp;in). Bust 78 cm (31 in), waist 63 cm (25 in); wearing EU 36.

**Etymology**: English *burgundy* + Latin *-ia*, for Latin feel. Identical to Latin *Burgundia*, the geographic region of France from which the color burgundy gets its name.

**Specimens examined**

**Holotype**:
***Silversaga 2021.497.12*** &mdash; Photograph.
800&times;1200.
EXIF metadata stripped.
Ventral view. Studio lighting against white background.
Subject's arms mostly adducted, facing right. Hair tied dorsally. Ribbon on belt worn ventrally.
*Argelisabethia burgundia* wb. unknown, 2021. &copy; Jessica Silversaga or unknown photographer, 2021, all rights reserved.
**Page**: ;
**SHA2-256**: `4ae55551fe55e11fdf495e1851428f615f3fea30d98e4c31e872ce1694b6e0b6`{.hash}
**Original**: <https://silversaga.se/cdn/shop/products/Jessica_Silversaga_FALL2021.jpg?v=1641480593>;
**IA**: <https://web.archive.org/web/20260409165940/https://silversaga.se/cdn/shop/products/Jessica_Silversaga_FALL2021.jpg?v=1641480593>;

***Silversaga 2021.497.32*** &mdash; Photograph.
800&times;1200.
EXIF metadata stripped.
Ventral view. Studio lighting against white background.
Subject's left arm positioned dorsally with right arm on chest, obscuring button row. Waist belt not visible; likely detached or placed behind garment.
*Argelisabethia burgundia* wb. unknown, 2021. &copy; Jessica Silversaga or unknown photographer, 2021, all rights reserved.
**Page**: ;
**SHA2-256**: `3b592ca86a316064735ff9877d09c8e864e8aab4ee8ec97d249e0bc1e796689e`{.hash}
**Original**: <https://silversaga.se/cdn/shop/products/Jessica_Silversaga_FALL2021_4.jpg?v=1641480597>;
**IA**: <https://web.archive.org/web/20260409170000/https://silversaga.se/cdn/shop/products/Jessica_Silversaga_FALL2021_4.jpg?v=1641480597>;

***Silversaga 2021.497.37*** &mdash; Photograph.
800&times;1200.
EXIF metadata stripped.
Dorsal view. Studio lighting against white background.
Subject's arms adducted. Hair tied ventrally. Waist belt worn with ribbon positioned at dorsal medial point.
*Argelisabethia burgundia* wb. unknown, 2021. &copy; Jessica Silversaga or unknown photographer, 2021, all rights reserved.
**Page**: ;
**SHA2-256**: `98413f1c50c34647fced776240f664e26d900d4a4c8dd11090f21cf8f164df0a`{.hash}
**Original**: <https://silversaga.se/cdn/shop/products/Jessica_Silversaga_FALL2021_2-1.jpg?v=1641480595>;
**IA**: <https://web.archive.org/web/20260409170003/https://silversaga.se/cdn/shop/products/Jessica_Silversaga_FALL2021_2-1.jpg?v=1641480595>;

***Silversaga 2021.497.41*** &mdash; Photograph.
800&times;1200.
EXIF metadata stripped.
Ventral view. Studio lighting against white background.
Subject's right arm holding skirt out. Left arm unseen. Hair tied ventrally; subject facing to her left, or to the right from camera perspective. Waist belt not worn.
*Argelisabethia burgundia* wb. unknown, 2021. &copy; Jessica Silversaga or unknown photographer, 2021, all rights reserved.
**Page**: ;
**SHA2-256**: `8d017e332b7e4fa64f7356c2664d6aa4e4fd7fcc04590f0606c3391bb42e8294`{.hash}

**Original**: <https://silversaga.se/cdn/shop/products/Jessica_Silversaga_FALL2021_6.jpg?v=1641480599>;
**IA**: <https://web.archive.org/web/20260409170034/https://silversaga.se/cdn/shop/products/Jessica_Silversaga_FALL2021_6.jpg?v=1641480599>;

***Silversaga 2021.497.85*** &mdash; Photograph.
800&times;1200.
EXIF metadata stripped.
Ventral view. Studio lighting against white background.
Truncated ventral view. Subject's left arm on chin and neck. Lateral surface seams <!-- SEAMS. NOT A TYPO! --> visible, though zipper is not.
Hair entirely out of frame. Waist belt worn, with ribbon at ventral medial point.
*Argelisabethia burgundia* wb. unknown, 2021. &copy; Jessica Silversaga or unknown photographer, 2021, all rights reserved.
**Page**: ;
**SHA2-256**: `600f646f5b8b2db20dbfe037672adc48c71b7a5f3516092cf7b19a530ba8b937`{.hash}
**Original**: <https://silversaga.se/cdn/shop/products/Jessica_Silversaga_FALL2021_3.jpg?v=1641480591>;
**IA**: <https://web.archive.org/web/20260409170036/https://silversaga.se/cdn/shop/products/Jessica_Silversaga_FALL2021_3.jpg?v=1641480591>;

<!--
remember, you can always cut-and-paste into a new monograph.
-->
### Family Celestidae
**Celestidae** Lemuria, 2026

**Remarks**: Celestidae, the Celeste Dress & Top (no. 198^[Internal incrementing identifier used by Silversaga. Silversaga does not use the numeric naming convention for marketing.]), was the newest pattern in Silversaga's repertoire when work began on the monograph. There was significant consideration as to whether Celestidae should be excluded from the monograph, due to its 16 views and 12 pattern hacks totalling to nearly 192 genera. It was eventually decided that the monograph would include Celestidae.

The Celeste first arose in the summer of 2025 (roughly June&ndash;August in Sweden, and possibly the northern hemisphere), and was dormant due to unspecified events in Silversaga's life. Work resumed at the start of 2026; on January 27, Silversaga began recruiting pattern testers for the Celeste. [@silversaga_celestetesters]. The Celeste was eventually released on April 1, 2026 [@silversaga_celeste2026].

The morphological diversity of the Celestidae remains unbound: though 12 of the base variants are known and the other four can be inferred; the pattern PDF includes another 12 pattern hacks, leading to a lower bound of 192 taxa. The previews on the product page only show 12 variants.

***Abbreviations.*** WR: waist row; WRt: waist row tie.
<!--
```{=latex}
\end{multicols}
```

::: {#tbl-panel layout-ncol=2}

| Character | Possibilities
|---|---|
| Dress len. | dress, top
| Sleeve len. | long, short
| Waist rows | one, two
| Waist row ties  | absent, present

: Celestidae characters {#tbl-celestidae-chars}


| Sleeve len. | WR | WRt | Taxon
|---|---|---|
| long | one | absent | 
| long | one | present | 
| long | two | absent | 
| long | two | present | 
| short | one | absent | 
| short | one | present | 
| short | two | absent | 
| short | two | present | 

: Celestidae matrix {#tbl-celestidae-matrix}

Characters and taxa for the Celestidae
:::

```{=latex}
\begin{multicols}{2}
``` 
-->

The yoke is always present; this is an invariant character.

**Description**: Neckline terminates inferior to neck. Manubrium and both scapulae covered. Fitted yoke with gathers. Skirt either A-line or slightly flared peplum hem. Optional bilateral inseam pockets. Dorsal medial button closure; adjustable; zippers entirely absent. 

**Etymology**: From Celeste + *-idae*, family suffix.

The name of the Celeste itself was crowdsourced in an Instagram post where Silversaga solicited ideas for her next pattern's name from the community [@silversaga_helpmename]. Among the 248 comments was one from Charis Bean Duke, an American composer, pianist, and sewist, under the Instagram account &commat;[`pianogirlxf`{.hash}](https://instagram.com/pianogirlxf), who suggested the name Celeste, which Silversaga chose.

#### Genus *Truncelestia*
***Truncelestia*** Lemuria, 2026; gen. nov.

**Diagnosis**: *Truncelestia* is distinguished from *Celestia* by the lack of a skirt.

#### Genus *Celestia*
***Celestia*** Lemuria, 2026; gen. nov.

**Diagnosis**: *Celestia* is distinguished from *Truncelestia* by the presence of a skirt.



```{=latex}
\newpage
```

# General remarks
## Filenames
Jessica's naming conventions for patterns are consistent at the pattern-level, but inconsistent as a whole.

For the Ella, Chloe, Celeste, ... patterns, we observed a numerical naming convention, and were thus unable to obtain their names.




<!--
TODO: Identify all gallery naming conventions for all 15 patterns
-->

Many filenames include the names of the pattern testers, which allows identification of the wearers.
<!--
Juliette
-->

## Names
### Laural? Stapleton
In the filenames, we consistently observed the spelling *Laural* for *Laural Stapleton*. We do not have information on Stapleton; nor whether *Laural* is the correct spelling of her name. Possible names used by Stapleton include *Laura*, *Laurel*, and *Lauren*. We have chosen to abbreviate her by her last name, *Stapleton*, as the spelling is significantly more plausible.

# Appendix
## Person abbreviations {#sec-person-abbr}
We define the following new person abbreviations:

* **Anja.S.** &mdash; Anja Scheithauer
* **Ashley.G.** &mdash; Ashley General
* **Stapleton** &mdash; Laural Stapleton
* **J.Silversaga** &mdash; Jessica Silversaga

## Acknowledgements
We used R; specifically, `ggtree`, to render tree figures. For information on `ggtree`, see @yuetal2017.

We thank Jessica Silversaga for her amazing patterns that help bolster a culture of home sewing and advance the slow fashion movement. We thank all the sewists, pattern testers, and the sources we have cited for documenting their projects in intricate detail.

We thank the people of the Archive Team (<https://wiki.archiveteam.org/wiki/Main_Page>) for assistance in archiving the Silversaga website and making it available through the Wayback Machine.

We thank the people of the Coffee Shop on [4d2.org](https://4d2.org), where our lead author has posted fragments of the paper time and time again, for being absolutely wonderful people, and being an extra set of eyes to keep errors shallow under Linus's law; and we thank Sarah, the operator of 4d2, for fostering such a wonderful space.

## Information
*Lemuria's (Informal) Journal of Clothing Taxonomy* is the gray literature journal of the First Lemurian Clothing Taxonomy, a system by Lemuria to assign Latin names to dresses using biological methods. The author, known mononymically as just Lemuria, is an Filipino programmer and independent gray literature researcher from Manila.

**Disclaimer**: *Lemuria's (Informal) Journal of Clothing Taxonomy* is a non-peer-reviewed, single-author, citizen science/gray literature publication with no institutional backing.

<!-- Publisher article ID: 2026.0007 -->

At publication, the journal did not have a DOI prefix.

Work began on the paper on 2026-04-08 and was published ...

* Visit us at: <https://lct01.lemuria.ph>
* Version control: <https://github.com/a-random-lemurian/lct01.lemuria.ph>
* Zenodo: <https://zenodo.org/communities/lct01>

&copy; Lemuria 2026. All original text and image content by Lemuria is licensed under CC BY-SA 4.0, unless explicitly noted. Linked images and other content are &copy; their respective owners or copyright holders.

# References

::: {#refs}
:::

```{=latex}
\end{multicols}
```
